// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ledger/post_service.proto

package com.example.proto.ledger.post;

public final class PostServiceOuterClass {
  private PostServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ledger_PostTransactionRequestPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ledger_PostTransactionRequestPb_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ledger_PostTransactionReplyPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ledger_PostTransactionReplyPb_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ledger_LedgerEntryPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ledger_LedgerEntryPb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031ledger/post_service.proto\022\006ledger\032\032led" +
      "ger/ledger_common.proto\"\210\001\n\030PostTransact" +
      "ionRequestPb\022\032\n\022legerTransactionId\030\001 \001(\t" +
      "\022\023\n\013referenceId\030\002 \001(\t\022\023\n\013description\030\003 \001" +
      "(\t\022&\n\007entries\030\004 \003(\0132\025.ledger.LedgerEntry" +
      "Pb\"3\n\026PostTransactionReplyPb\022\014\n\004code\030\001 \001" +
      "(\005\022\013\n\003msg\030\002 \001(\t\"q\n\rLedgerEntryPb\022\021\n\tacco" +
      "untId\030\001 \001(\t\022,\n\tdirection\030\002 \001(\0162\031.ledger." +
      "LedgerDirectionPb\022\016\n\006amount\030\003 \001(\003\022\017\n\007ass" +
      "etId\030\004 \001(\t2d\n\013PostService\022U\n\017postTransac" +
      "tion\022 .ledger.PostTransactionRequestPb\032\036" +
      ".ledger.PostTransactionReplyPb\"\000B!\n\035com." +
      "example.proto.ledger.postP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.example.proto.ledger.common.LedgerCommon.getDescriptor(),
        });
    internal_static_ledger_PostTransactionRequestPb_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ledger_PostTransactionRequestPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ledger_PostTransactionRequestPb_descriptor,
        new java.lang.String[] { "LegerTransactionId", "ReferenceId", "Description", "Entries", });
    internal_static_ledger_PostTransactionReplyPb_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ledger_PostTransactionReplyPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ledger_PostTransactionReplyPb_descriptor,
        new java.lang.String[] { "Code", "Msg", });
    internal_static_ledger_LedgerEntryPb_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ledger_LedgerEntryPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ledger_LedgerEntryPb_descriptor,
        new java.lang.String[] { "AccountId", "Direction", "Amount", "AssetId", });
    com.example.proto.ledger.common.LedgerCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
