// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ledger/post_service.proto

package com.example.proto.ledger.post;

public interface PostTransactionRequestPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ledger.PostTransactionRequestPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string legerTransactionId = 1;</code>
   * @return The legerTransactionId.
   */
  java.lang.String getLegerTransactionId();
  /**
   * <code>string legerTransactionId = 1;</code>
   * @return The bytes for legerTransactionId.
   */
  com.google.protobuf.ByteString
      getLegerTransactionIdBytes();

  /**
   * <code>string referenceId = 2;</code>
   * @return The referenceId.
   */
  java.lang.String getReferenceId();
  /**
   * <code>string referenceId = 2;</code>
   * @return The bytes for referenceId.
   */
  com.google.protobuf.ByteString
      getReferenceIdBytes();

  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>repeated .ledger.LedgerEntryPb entries = 4;</code>
   */
  java.util.List<com.example.proto.ledger.post.LedgerEntryPb> 
      getEntriesList();
  /**
   * <code>repeated .ledger.LedgerEntryPb entries = 4;</code>
   */
  com.example.proto.ledger.post.LedgerEntryPb getEntries(int index);
  /**
   * <code>repeated .ledger.LedgerEntryPb entries = 4;</code>
   */
  int getEntriesCount();
  /**
   * <code>repeated .ledger.LedgerEntryPb entries = 4;</code>
   */
  java.util.List<? extends com.example.proto.ledger.post.LedgerEntryPbOrBuilder> 
      getEntriesOrBuilderList();
  /**
   * <code>repeated .ledger.LedgerEntryPb entries = 4;</code>
   */
  com.example.proto.ledger.post.LedgerEntryPbOrBuilder getEntriesOrBuilder(
      int index);
}
