syntax = "proto3";

package common;

option java_multiple_files = true;
option java_package = "com.exchange.proto.common.error";

message ErrorPb {
  ErrorCodePb code = 1;
  string message = 2;
  string detail = 3;
}

enum ErrorCodePb {
  ERROR_OK = 0;

  // internal
  ERROR_INTERNAL = 1;
  ERROR_UNAVAILABLE = 2;

  // 1xxx business condition violations
  ERROR_FAILED_PRECONDITION = 1000;  // use this error when you need a generic error for business logic but don't care about the specific reason
  ERROR_CONFLICT = 1001;
  ERROR_PROCESSING = 1002; // for example, another request with same params is in processing

  // 2xxx validation
  ERROR_INVALID_ARGUMENT = 2000;
  ERROR_UNAUTHENTICATED = 2001;
  ERROR_UNAUTHORIZED = 2002;

  // 2xxx resource issues
  ERROR_NOT_FOUND = 3000;
  ERROR_ALREADY_EXISTS = 3001;
}
