// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet/create_wallet.proto

package com.exchange.proto.wallet.wallet;

/**
 * Protobuf type {@code wallet.CreateWalletRequestPb}
 */
public final class CreateWalletRequestPb extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:wallet.CreateWalletRequestPb)
    CreateWalletRequestPbOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateWalletRequestPb.newBuilder() to construct.
  private CreateWalletRequestPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateWalletRequestPb() {
    serviceId_ = 0;
    referenceId_ = "";
    assetId_ = "";
    ownerType_ = 0;
    ownerId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateWalletRequestPb();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateWalletRequestPb(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            serviceId_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            referenceId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            assetId_ = s;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            ownerType_ = rawValue;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            ownerId_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.exchange.proto.wallet.wallet.CreateWallet.internal_static_wallet_CreateWalletRequestPb_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.exchange.proto.wallet.wallet.CreateWallet.internal_static_wallet_CreateWalletRequestPb_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.exchange.proto.wallet.wallet.CreateWalletRequestPb.class, com.exchange.proto.wallet.wallet.CreateWalletRequestPb.Builder.class);
  }

  public static final int SERVICE_ID_FIELD_NUMBER = 1;
  private int serviceId_;
  /**
   * <code>.wallet.ServiceIdPb service_id = 1;</code>
   * @return The enum numeric value on the wire for serviceId.
   */
  @java.lang.Override public int getServiceIdValue() {
    return serviceId_;
  }
  /**
   * <code>.wallet.ServiceIdPb service_id = 1;</code>
   * @return The serviceId.
   */
  @java.lang.Override public com.exchange.proto.wallet.common.ServiceIdPb getServiceId() {
    @SuppressWarnings("deprecation")
    com.exchange.proto.wallet.common.ServiceIdPb result = com.exchange.proto.wallet.common.ServiceIdPb.valueOf(serviceId_);
    return result == null ? com.exchange.proto.wallet.common.ServiceIdPb.UNRECOGNIZED : result;
  }

  public static final int REFERENCE_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object referenceId_;
  /**
   * <code>string reference_id = 2;</code>
   * @return The referenceId.
   */
  @java.lang.Override
  public java.lang.String getReferenceId() {
    java.lang.Object ref = referenceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      referenceId_ = s;
      return s;
    }
  }
  /**
   * <code>string reference_id = 2;</code>
   * @return The bytes for referenceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReferenceIdBytes() {
    java.lang.Object ref = referenceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      referenceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ASSET_ID_FIELD_NUMBER = 3;
  private volatile java.lang.Object assetId_;
  /**
   * <code>string asset_id = 3;</code>
   * @return The assetId.
   */
  @java.lang.Override
  public java.lang.String getAssetId() {
    java.lang.Object ref = assetId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      assetId_ = s;
      return s;
    }
  }
  /**
   * <code>string asset_id = 3;</code>
   * @return The bytes for assetId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAssetIdBytes() {
    java.lang.Object ref = assetId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      assetId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OWNER_TYPE_FIELD_NUMBER = 4;
  private int ownerType_;
  /**
   * <code>.wallet.OwnerTypePb owner_type = 4;</code>
   * @return The enum numeric value on the wire for ownerType.
   */
  @java.lang.Override public int getOwnerTypeValue() {
    return ownerType_;
  }
  /**
   * <code>.wallet.OwnerTypePb owner_type = 4;</code>
   * @return The ownerType.
   */
  @java.lang.Override public com.exchange.proto.wallet.common.OwnerTypePb getOwnerType() {
    @SuppressWarnings("deprecation")
    com.exchange.proto.wallet.common.OwnerTypePb result = com.exchange.proto.wallet.common.OwnerTypePb.valueOf(ownerType_);
    return result == null ? com.exchange.proto.wallet.common.OwnerTypePb.UNRECOGNIZED : result;
  }

  public static final int OWNER_ID_FIELD_NUMBER = 5;
  private volatile java.lang.Object ownerId_;
  /**
   * <code>string owner_id = 5;</code>
   * @return The ownerId.
   */
  @java.lang.Override
  public java.lang.String getOwnerId() {
    java.lang.Object ref = ownerId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ownerId_ = s;
      return s;
    }
  }
  /**
   * <code>string owner_id = 5;</code>
   * @return The bytes for ownerId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOwnerIdBytes() {
    java.lang.Object ref = ownerId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ownerId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (serviceId_ != com.exchange.proto.wallet.common.ServiceIdPb.ServiceIdPb_Unknown.getNumber()) {
      output.writeEnum(1, serviceId_);
    }
    if (!getReferenceIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, referenceId_);
    }
    if (!getAssetIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, assetId_);
    }
    if (ownerType_ != com.exchange.proto.wallet.common.OwnerTypePb.OwnerTypePb_Unknown.getNumber()) {
      output.writeEnum(4, ownerType_);
    }
    if (!getOwnerIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, ownerId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (serviceId_ != com.exchange.proto.wallet.common.ServiceIdPb.ServiceIdPb_Unknown.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, serviceId_);
    }
    if (!getReferenceIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, referenceId_);
    }
    if (!getAssetIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, assetId_);
    }
    if (ownerType_ != com.exchange.proto.wallet.common.OwnerTypePb.OwnerTypePb_Unknown.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, ownerType_);
    }
    if (!getOwnerIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, ownerId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.exchange.proto.wallet.wallet.CreateWalletRequestPb)) {
      return super.equals(obj);
    }
    com.exchange.proto.wallet.wallet.CreateWalletRequestPb other = (com.exchange.proto.wallet.wallet.CreateWalletRequestPb) obj;

    if (serviceId_ != other.serviceId_) return false;
    if (!getReferenceId()
        .equals(other.getReferenceId())) return false;
    if (!getAssetId()
        .equals(other.getAssetId())) return false;
    if (ownerType_ != other.ownerType_) return false;
    if (!getOwnerId()
        .equals(other.getOwnerId())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SERVICE_ID_FIELD_NUMBER;
    hash = (53 * hash) + serviceId_;
    hash = (37 * hash) + REFERENCE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getReferenceId().hashCode();
    hash = (37 * hash) + ASSET_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAssetId().hashCode();
    hash = (37 * hash) + OWNER_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + ownerType_;
    hash = (37 * hash) + OWNER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getOwnerId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.exchange.proto.wallet.wallet.CreateWalletRequestPb parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.exchange.proto.wallet.wallet.CreateWalletRequestPb parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.exchange.proto.wallet.wallet.CreateWalletRequestPb parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.exchange.proto.wallet.wallet.CreateWalletRequestPb parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.exchange.proto.wallet.wallet.CreateWalletRequestPb parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.exchange.proto.wallet.wallet.CreateWalletRequestPb parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.exchange.proto.wallet.wallet.CreateWalletRequestPb parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.exchange.proto.wallet.wallet.CreateWalletRequestPb parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.exchange.proto.wallet.wallet.CreateWalletRequestPb parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.exchange.proto.wallet.wallet.CreateWalletRequestPb parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.exchange.proto.wallet.wallet.CreateWalletRequestPb parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.exchange.proto.wallet.wallet.CreateWalletRequestPb parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.exchange.proto.wallet.wallet.CreateWalletRequestPb prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code wallet.CreateWalletRequestPb}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:wallet.CreateWalletRequestPb)
      com.exchange.proto.wallet.wallet.CreateWalletRequestPbOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.exchange.proto.wallet.wallet.CreateWallet.internal_static_wallet_CreateWalletRequestPb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.exchange.proto.wallet.wallet.CreateWallet.internal_static_wallet_CreateWalletRequestPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.exchange.proto.wallet.wallet.CreateWalletRequestPb.class, com.exchange.proto.wallet.wallet.CreateWalletRequestPb.Builder.class);
    }

    // Construct using com.exchange.proto.wallet.wallet.CreateWalletRequestPb.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      serviceId_ = 0;

      referenceId_ = "";

      assetId_ = "";

      ownerType_ = 0;

      ownerId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.exchange.proto.wallet.wallet.CreateWallet.internal_static_wallet_CreateWalletRequestPb_descriptor;
    }

    @java.lang.Override
    public com.exchange.proto.wallet.wallet.CreateWalletRequestPb getDefaultInstanceForType() {
      return com.exchange.proto.wallet.wallet.CreateWalletRequestPb.getDefaultInstance();
    }

    @java.lang.Override
    public com.exchange.proto.wallet.wallet.CreateWalletRequestPb build() {
      com.exchange.proto.wallet.wallet.CreateWalletRequestPb result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.exchange.proto.wallet.wallet.CreateWalletRequestPb buildPartial() {
      com.exchange.proto.wallet.wallet.CreateWalletRequestPb result = new com.exchange.proto.wallet.wallet.CreateWalletRequestPb(this);
      result.serviceId_ = serviceId_;
      result.referenceId_ = referenceId_;
      result.assetId_ = assetId_;
      result.ownerType_ = ownerType_;
      result.ownerId_ = ownerId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.exchange.proto.wallet.wallet.CreateWalletRequestPb) {
        return mergeFrom((com.exchange.proto.wallet.wallet.CreateWalletRequestPb)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.exchange.proto.wallet.wallet.CreateWalletRequestPb other) {
      if (other == com.exchange.proto.wallet.wallet.CreateWalletRequestPb.getDefaultInstance()) return this;
      if (other.serviceId_ != 0) {
        setServiceIdValue(other.getServiceIdValue());
      }
      if (!other.getReferenceId().isEmpty()) {
        referenceId_ = other.referenceId_;
        onChanged();
      }
      if (!other.getAssetId().isEmpty()) {
        assetId_ = other.assetId_;
        onChanged();
      }
      if (other.ownerType_ != 0) {
        setOwnerTypeValue(other.getOwnerTypeValue());
      }
      if (!other.getOwnerId().isEmpty()) {
        ownerId_ = other.ownerId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.exchange.proto.wallet.wallet.CreateWalletRequestPb parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.exchange.proto.wallet.wallet.CreateWalletRequestPb) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int serviceId_ = 0;
    /**
     * <code>.wallet.ServiceIdPb service_id = 1;</code>
     * @return The enum numeric value on the wire for serviceId.
     */
    @java.lang.Override public int getServiceIdValue() {
      return serviceId_;
    }
    /**
     * <code>.wallet.ServiceIdPb service_id = 1;</code>
     * @param value The enum numeric value on the wire for serviceId to set.
     * @return This builder for chaining.
     */
    public Builder setServiceIdValue(int value) {
      
      serviceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.wallet.ServiceIdPb service_id = 1;</code>
     * @return The serviceId.
     */
    @java.lang.Override
    public com.exchange.proto.wallet.common.ServiceIdPb getServiceId() {
      @SuppressWarnings("deprecation")
      com.exchange.proto.wallet.common.ServiceIdPb result = com.exchange.proto.wallet.common.ServiceIdPb.valueOf(serviceId_);
      return result == null ? com.exchange.proto.wallet.common.ServiceIdPb.UNRECOGNIZED : result;
    }
    /**
     * <code>.wallet.ServiceIdPb service_id = 1;</code>
     * @param value The serviceId to set.
     * @return This builder for chaining.
     */
    public Builder setServiceId(com.exchange.proto.wallet.common.ServiceIdPb value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      serviceId_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.wallet.ServiceIdPb service_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearServiceId() {
      
      serviceId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object referenceId_ = "";
    /**
     * <code>string reference_id = 2;</code>
     * @return The referenceId.
     */
    public java.lang.String getReferenceId() {
      java.lang.Object ref = referenceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        referenceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string reference_id = 2;</code>
     * @return The bytes for referenceId.
     */
    public com.google.protobuf.ByteString
        getReferenceIdBytes() {
      java.lang.Object ref = referenceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        referenceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string reference_id = 2;</code>
     * @param value The referenceId to set.
     * @return This builder for chaining.
     */
    public Builder setReferenceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      referenceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string reference_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearReferenceId() {
      
      referenceId_ = getDefaultInstance().getReferenceId();
      onChanged();
      return this;
    }
    /**
     * <code>string reference_id = 2;</code>
     * @param value The bytes for referenceId to set.
     * @return This builder for chaining.
     */
    public Builder setReferenceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      referenceId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object assetId_ = "";
    /**
     * <code>string asset_id = 3;</code>
     * @return The assetId.
     */
    public java.lang.String getAssetId() {
      java.lang.Object ref = assetId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        assetId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string asset_id = 3;</code>
     * @return The bytes for assetId.
     */
    public com.google.protobuf.ByteString
        getAssetIdBytes() {
      java.lang.Object ref = assetId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        assetId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string asset_id = 3;</code>
     * @param value The assetId to set.
     * @return This builder for chaining.
     */
    public Builder setAssetId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      assetId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string asset_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAssetId() {
      
      assetId_ = getDefaultInstance().getAssetId();
      onChanged();
      return this;
    }
    /**
     * <code>string asset_id = 3;</code>
     * @param value The bytes for assetId to set.
     * @return This builder for chaining.
     */
    public Builder setAssetIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      assetId_ = value;
      onChanged();
      return this;
    }

    private int ownerType_ = 0;
    /**
     * <code>.wallet.OwnerTypePb owner_type = 4;</code>
     * @return The enum numeric value on the wire for ownerType.
     */
    @java.lang.Override public int getOwnerTypeValue() {
      return ownerType_;
    }
    /**
     * <code>.wallet.OwnerTypePb owner_type = 4;</code>
     * @param value The enum numeric value on the wire for ownerType to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerTypeValue(int value) {
      
      ownerType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.wallet.OwnerTypePb owner_type = 4;</code>
     * @return The ownerType.
     */
    @java.lang.Override
    public com.exchange.proto.wallet.common.OwnerTypePb getOwnerType() {
      @SuppressWarnings("deprecation")
      com.exchange.proto.wallet.common.OwnerTypePb result = com.exchange.proto.wallet.common.OwnerTypePb.valueOf(ownerType_);
      return result == null ? com.exchange.proto.wallet.common.OwnerTypePb.UNRECOGNIZED : result;
    }
    /**
     * <code>.wallet.OwnerTypePb owner_type = 4;</code>
     * @param value The ownerType to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerType(com.exchange.proto.wallet.common.OwnerTypePb value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      ownerType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.wallet.OwnerTypePb owner_type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearOwnerType() {
      
      ownerType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object ownerId_ = "";
    /**
     * <code>string owner_id = 5;</code>
     * @return The ownerId.
     */
    public java.lang.String getOwnerId() {
      java.lang.Object ref = ownerId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ownerId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string owner_id = 5;</code>
     * @return The bytes for ownerId.
     */
    public com.google.protobuf.ByteString
        getOwnerIdBytes() {
      java.lang.Object ref = ownerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ownerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string owner_id = 5;</code>
     * @param value The ownerId to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ownerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string owner_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearOwnerId() {
      
      ownerId_ = getDefaultInstance().getOwnerId();
      onChanged();
      return this;
    }
    /**
     * <code>string owner_id = 5;</code>
     * @param value The bytes for ownerId to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ownerId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:wallet.CreateWalletRequestPb)
  }

  // @@protoc_insertion_point(class_scope:wallet.CreateWalletRequestPb)
  private static final com.exchange.proto.wallet.wallet.CreateWalletRequestPb DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.exchange.proto.wallet.wallet.CreateWalletRequestPb();
  }

  public static com.exchange.proto.wallet.wallet.CreateWalletRequestPb getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateWalletRequestPb>
      PARSER = new com.google.protobuf.AbstractParser<CreateWalletRequestPb>() {
    @java.lang.Override
    public CreateWalletRequestPb parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateWalletRequestPb(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateWalletRequestPb> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateWalletRequestPb> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.exchange.proto.wallet.wallet.CreateWalletRequestPb getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

