// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet/create_wallet.proto

package com.exchange.proto.wallet.wallet;

public final class CreateWallet {
  private CreateWallet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_CreateWalletRequestPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wallet_CreateWalletRequestPb_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_CreateWalletReplyPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wallet_CreateWalletReplyPb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032wallet/create_wallet.proto\022\006wallet\032\030wa" +
      "llet/wallet_enum.proto\032%com/exchange/pro" +
      "to/common/error.proto\"\243\001\n\025CreateWalletRe" +
      "questPb\022\'\n\nservice_id\030\001 \001(\0162\023.wallet.Ser" +
      "viceIdPb\022\024\n\014reference_id\030\002 \001(\t\022\020\n\010asset_" +
      "id\030\003 \001(\t\022\'\n\nowner_type\030\004 \001(\0162\023.wallet.Ow" +
      "nerTypePb\022\020\n\010owner_id\030\005 \001(\t\"5\n\023CreateWal" +
      "letReplyPb\022\036\n\005error\030\001 \001(\0132\017.common.Error" +
      "PbB$\n com.exchange.proto.wallet.walletP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.exchange.proto.wallet.common.WalletEnum.getDescriptor(),
          com.exchange.proto.common.error.Error.getDescriptor(),
        });
    internal_static_wallet_CreateWalletRequestPb_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_wallet_CreateWalletRequestPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wallet_CreateWalletRequestPb_descriptor,
        new java.lang.String[] { "ServiceId", "ReferenceId", "AssetId", "OwnerType", "OwnerId", });
    internal_static_wallet_CreateWalletReplyPb_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_wallet_CreateWalletReplyPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wallet_CreateWalletReplyPb_descriptor,
        new java.lang.String[] { "Error", });
    com.exchange.proto.wallet.common.WalletEnum.getDescriptor();
    com.exchange.proto.common.error.Error.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
