// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet/wallet_transaction.proto

package com.exchange.proto.wallet.wallet;

public interface ReservationInfoPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wallet.ReservationInfoPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reservation_ref = 1;</code>
   * @return The reservationRef.
   */
  java.lang.String getReservationRef();
  /**
   * <code>string reservation_ref = 1;</code>
   * @return The bytes for reservationRef.
   */
  com.google.protobuf.ByteString
      getReservationRefBytes();

  /**
   * <code>string wallet_ref = 2;</code>
   * @return The walletRef.
   */
  java.lang.String getWalletRef();
  /**
   * <code>string wallet_ref = 2;</code>
   * @return The bytes for walletRef.
   */
  com.google.protobuf.ByteString
      getWalletRefBytes();

  /**
   * <code>string asset_code = 3;</code>
   * @return The assetCode.
   */
  java.lang.String getAssetCode();
  /**
   * <code>string asset_code = 3;</code>
   * @return The bytes for assetCode.
   */
  com.google.protobuf.ByteString
      getAssetCodeBytes();

  /**
   * <code>int64 amount = 4;</code>
   * @return The amount.
   */
  long getAmount();
}
