// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet/wallet_transaction.proto

package com.exchange.proto.wallet.wallet;

/**
 * Protobuf type {@code wallet.ReserveTransactionReplyPb}
 */
public final class ReserveTransactionReplyPb extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:wallet.ReserveTransactionReplyPb)
    ReserveTransactionReplyPbOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReserveTransactionReplyPb.newBuilder() to construct.
  private ReserveTransactionReplyPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReserveTransactionReplyPb() {
    transactionId_ = "";
    status_ = 0;
    infos_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ReserveTransactionReplyPb();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReserveTransactionReplyPb(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.exchange.proto.common.error.ErrorPb.Builder subBuilder = null;
            if (error_ != null) {
              subBuilder = error_.toBuilder();
            }
            error_ = input.readMessage(com.exchange.proto.common.error.ErrorPb.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(error_);
              error_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            transactionId_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              infos_ = new java.util.ArrayList<com.exchange.proto.wallet.wallet.ReservationInfoPb>();
              mutable_bitField0_ |= 0x00000001;
            }
            infos_.add(
                input.readMessage(com.exchange.proto.wallet.wallet.ReservationInfoPb.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        infos_ = java.util.Collections.unmodifiableList(infos_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.exchange.proto.wallet.wallet.WalletTransaction.internal_static_wallet_ReserveTransactionReplyPb_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.exchange.proto.wallet.wallet.WalletTransaction.internal_static_wallet_ReserveTransactionReplyPb_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb.class, com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb.Builder.class);
  }

  public static final int ERROR_FIELD_NUMBER = 1;
  private com.exchange.proto.common.error.ErrorPb error_;
  /**
   * <code>.common.ErrorPb error = 1;</code>
   * @return Whether the error field is set.
   */
  @java.lang.Override
  public boolean hasError() {
    return error_ != null;
  }
  /**
   * <code>.common.ErrorPb error = 1;</code>
   * @return The error.
   */
  @java.lang.Override
  public com.exchange.proto.common.error.ErrorPb getError() {
    return error_ == null ? com.exchange.proto.common.error.ErrorPb.getDefaultInstance() : error_;
  }
  /**
   * <code>.common.ErrorPb error = 1;</code>
   */
  @java.lang.Override
  public com.exchange.proto.common.error.ErrorPbOrBuilder getErrorOrBuilder() {
    return getError();
  }

  public static final int TRANSACTION_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object transactionId_;
  /**
   * <code>string transaction_id = 2;</code>
   * @return The transactionId.
   */
  @java.lang.Override
  public java.lang.String getTransactionId() {
    java.lang.Object ref = transactionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      transactionId_ = s;
      return s;
    }
  }
  /**
   * <code>string transaction_id = 2;</code>
   * @return The bytes for transactionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTransactionIdBytes() {
    java.lang.Object ref = transactionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      transactionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 3;
  private int status_;
  /**
   * <code>.wallet.TransactionStatusPb status = 3;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.wallet.TransactionStatusPb status = 3;</code>
   * @return The status.
   */
  @java.lang.Override public com.exchange.proto.wallet.common.TransactionStatusPb getStatus() {
    @SuppressWarnings("deprecation")
    com.exchange.proto.wallet.common.TransactionStatusPb result = com.exchange.proto.wallet.common.TransactionStatusPb.valueOf(status_);
    return result == null ? com.exchange.proto.wallet.common.TransactionStatusPb.UNRECOGNIZED : result;
  }

  public static final int INFOS_FIELD_NUMBER = 4;
  private java.util.List<com.exchange.proto.wallet.wallet.ReservationInfoPb> infos_;
  /**
   * <code>repeated .wallet.ReservationInfoPb infos = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.exchange.proto.wallet.wallet.ReservationInfoPb> getInfosList() {
    return infos_;
  }
  /**
   * <code>repeated .wallet.ReservationInfoPb infos = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.exchange.proto.wallet.wallet.ReservationInfoPbOrBuilder> 
      getInfosOrBuilderList() {
    return infos_;
  }
  /**
   * <code>repeated .wallet.ReservationInfoPb infos = 4;</code>
   */
  @java.lang.Override
  public int getInfosCount() {
    return infos_.size();
  }
  /**
   * <code>repeated .wallet.ReservationInfoPb infos = 4;</code>
   */
  @java.lang.Override
  public com.exchange.proto.wallet.wallet.ReservationInfoPb getInfos(int index) {
    return infos_.get(index);
  }
  /**
   * <code>repeated .wallet.ReservationInfoPb infos = 4;</code>
   */
  @java.lang.Override
  public com.exchange.proto.wallet.wallet.ReservationInfoPbOrBuilder getInfosOrBuilder(
      int index) {
    return infos_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (error_ != null) {
      output.writeMessage(1, getError());
    }
    if (!getTransactionIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, transactionId_);
    }
    if (status_ != com.exchange.proto.wallet.common.TransactionStatusPb.TransactionStatusPb_Unknown.getNumber()) {
      output.writeEnum(3, status_);
    }
    for (int i = 0; i < infos_.size(); i++) {
      output.writeMessage(4, infos_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (error_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getError());
    }
    if (!getTransactionIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, transactionId_);
    }
    if (status_ != com.exchange.proto.wallet.common.TransactionStatusPb.TransactionStatusPb_Unknown.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, status_);
    }
    for (int i = 0; i < infos_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, infos_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb)) {
      return super.equals(obj);
    }
    com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb other = (com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb) obj;

    if (hasError() != other.hasError()) return false;
    if (hasError()) {
      if (!getError()
          .equals(other.getError())) return false;
    }
    if (!getTransactionId()
        .equals(other.getTransactionId())) return false;
    if (status_ != other.status_) return false;
    if (!getInfosList()
        .equals(other.getInfosList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    hash = (37 * hash) + TRANSACTION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTransactionId().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    if (getInfosCount() > 0) {
      hash = (37 * hash) + INFOS_FIELD_NUMBER;
      hash = (53 * hash) + getInfosList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code wallet.ReserveTransactionReplyPb}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:wallet.ReserveTransactionReplyPb)
      com.exchange.proto.wallet.wallet.ReserveTransactionReplyPbOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.exchange.proto.wallet.wallet.WalletTransaction.internal_static_wallet_ReserveTransactionReplyPb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.exchange.proto.wallet.wallet.WalletTransaction.internal_static_wallet_ReserveTransactionReplyPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb.class, com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb.Builder.class);
    }

    // Construct using com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getInfosFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (errorBuilder_ == null) {
        error_ = null;
      } else {
        error_ = null;
        errorBuilder_ = null;
      }
      transactionId_ = "";

      status_ = 0;

      if (infosBuilder_ == null) {
        infos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        infosBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.exchange.proto.wallet.wallet.WalletTransaction.internal_static_wallet_ReserveTransactionReplyPb_descriptor;
    }

    @java.lang.Override
    public com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb getDefaultInstanceForType() {
      return com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb.getDefaultInstance();
    }

    @java.lang.Override
    public com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb build() {
      com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb buildPartial() {
      com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb result = new com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb(this);
      int from_bitField0_ = bitField0_;
      if (errorBuilder_ == null) {
        result.error_ = error_;
      } else {
        result.error_ = errorBuilder_.build();
      }
      result.transactionId_ = transactionId_;
      result.status_ = status_;
      if (infosBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          infos_ = java.util.Collections.unmodifiableList(infos_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.infos_ = infos_;
      } else {
        result.infos_ = infosBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb) {
        return mergeFrom((com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb other) {
      if (other == com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb.getDefaultInstance()) return this;
      if (other.hasError()) {
        mergeError(other.getError());
      }
      if (!other.getTransactionId().isEmpty()) {
        transactionId_ = other.transactionId_;
        onChanged();
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (infosBuilder_ == null) {
        if (!other.infos_.isEmpty()) {
          if (infos_.isEmpty()) {
            infos_ = other.infos_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureInfosIsMutable();
            infos_.addAll(other.infos_);
          }
          onChanged();
        }
      } else {
        if (!other.infos_.isEmpty()) {
          if (infosBuilder_.isEmpty()) {
            infosBuilder_.dispose();
            infosBuilder_ = null;
            infos_ = other.infos_;
            bitField0_ = (bitField0_ & ~0x00000001);
            infosBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getInfosFieldBuilder() : null;
          } else {
            infosBuilder_.addAllMessages(other.infos_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.exchange.proto.common.error.ErrorPb error_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.exchange.proto.common.error.ErrorPb, com.exchange.proto.common.error.ErrorPb.Builder, com.exchange.proto.common.error.ErrorPbOrBuilder> errorBuilder_;
    /**
     * <code>.common.ErrorPb error = 1;</code>
     * @return Whether the error field is set.
     */
    public boolean hasError() {
      return errorBuilder_ != null || error_ != null;
    }
    /**
     * <code>.common.ErrorPb error = 1;</code>
     * @return The error.
     */
    public com.exchange.proto.common.error.ErrorPb getError() {
      if (errorBuilder_ == null) {
        return error_ == null ? com.exchange.proto.common.error.ErrorPb.getDefaultInstance() : error_;
      } else {
        return errorBuilder_.getMessage();
      }
    }
    /**
     * <code>.common.ErrorPb error = 1;</code>
     */
    public Builder setError(com.exchange.proto.common.error.ErrorPb value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        error_ = value;
        onChanged();
      } else {
        errorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.common.ErrorPb error = 1;</code>
     */
    public Builder setError(
        com.exchange.proto.common.error.ErrorPb.Builder builderForValue) {
      if (errorBuilder_ == null) {
        error_ = builderForValue.build();
        onChanged();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.common.ErrorPb error = 1;</code>
     */
    public Builder mergeError(com.exchange.proto.common.error.ErrorPb value) {
      if (errorBuilder_ == null) {
        if (error_ != null) {
          error_ =
            com.exchange.proto.common.error.ErrorPb.newBuilder(error_).mergeFrom(value).buildPartial();
        } else {
          error_ = value;
        }
        onChanged();
      } else {
        errorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.common.ErrorPb error = 1;</code>
     */
    public Builder clearError() {
      if (errorBuilder_ == null) {
        error_ = null;
        onChanged();
      } else {
        error_ = null;
        errorBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.common.ErrorPb error = 1;</code>
     */
    public com.exchange.proto.common.error.ErrorPb.Builder getErrorBuilder() {
      
      onChanged();
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <code>.common.ErrorPb error = 1;</code>
     */
    public com.exchange.proto.common.error.ErrorPbOrBuilder getErrorOrBuilder() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        return error_ == null ?
            com.exchange.proto.common.error.ErrorPb.getDefaultInstance() : error_;
      }
    }
    /**
     * <code>.common.ErrorPb error = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.exchange.proto.common.error.ErrorPb, com.exchange.proto.common.error.ErrorPb.Builder, com.exchange.proto.common.error.ErrorPbOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.exchange.proto.common.error.ErrorPb, com.exchange.proto.common.error.ErrorPb.Builder, com.exchange.proto.common.error.ErrorPbOrBuilder>(
                getError(),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }

    private java.lang.Object transactionId_ = "";
    /**
     * <code>string transaction_id = 2;</code>
     * @return The transactionId.
     */
    public java.lang.String getTransactionId() {
      java.lang.Object ref = transactionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transactionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string transaction_id = 2;</code>
     * @return The bytes for transactionId.
     */
    public com.google.protobuf.ByteString
        getTransactionIdBytes() {
      java.lang.Object ref = transactionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transactionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string transaction_id = 2;</code>
     * @param value The transactionId to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      transactionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string transaction_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransactionId() {
      
      transactionId_ = getDefaultInstance().getTransactionId();
      onChanged();
      return this;
    }
    /**
     * <code>string transaction_id = 2;</code>
     * @param value The bytes for transactionId to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      transactionId_ = value;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.wallet.TransactionStatusPb status = 3;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.wallet.TransactionStatusPb status = 3;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.wallet.TransactionStatusPb status = 3;</code>
     * @return The status.
     */
    @java.lang.Override
    public com.exchange.proto.wallet.common.TransactionStatusPb getStatus() {
      @SuppressWarnings("deprecation")
      com.exchange.proto.wallet.common.TransactionStatusPb result = com.exchange.proto.wallet.common.TransactionStatusPb.valueOf(status_);
      return result == null ? com.exchange.proto.wallet.common.TransactionStatusPb.UNRECOGNIZED : result;
    }
    /**
     * <code>.wallet.TransactionStatusPb status = 3;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(com.exchange.proto.wallet.common.TransactionStatusPb value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.wallet.TransactionStatusPb status = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.exchange.proto.wallet.wallet.ReservationInfoPb> infos_ =
      java.util.Collections.emptyList();
    private void ensureInfosIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        infos_ = new java.util.ArrayList<com.exchange.proto.wallet.wallet.ReservationInfoPb>(infos_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.exchange.proto.wallet.wallet.ReservationInfoPb, com.exchange.proto.wallet.wallet.ReservationInfoPb.Builder, com.exchange.proto.wallet.wallet.ReservationInfoPbOrBuilder> infosBuilder_;

    /**
     * <code>repeated .wallet.ReservationInfoPb infos = 4;</code>
     */
    public java.util.List<com.exchange.proto.wallet.wallet.ReservationInfoPb> getInfosList() {
      if (infosBuilder_ == null) {
        return java.util.Collections.unmodifiableList(infos_);
      } else {
        return infosBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .wallet.ReservationInfoPb infos = 4;</code>
     */
    public int getInfosCount() {
      if (infosBuilder_ == null) {
        return infos_.size();
      } else {
        return infosBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .wallet.ReservationInfoPb infos = 4;</code>
     */
    public com.exchange.proto.wallet.wallet.ReservationInfoPb getInfos(int index) {
      if (infosBuilder_ == null) {
        return infos_.get(index);
      } else {
        return infosBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .wallet.ReservationInfoPb infos = 4;</code>
     */
    public Builder setInfos(
        int index, com.exchange.proto.wallet.wallet.ReservationInfoPb value) {
      if (infosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInfosIsMutable();
        infos_.set(index, value);
        onChanged();
      } else {
        infosBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .wallet.ReservationInfoPb infos = 4;</code>
     */
    public Builder setInfos(
        int index, com.exchange.proto.wallet.wallet.ReservationInfoPb.Builder builderForValue) {
      if (infosBuilder_ == null) {
        ensureInfosIsMutable();
        infos_.set(index, builderForValue.build());
        onChanged();
      } else {
        infosBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .wallet.ReservationInfoPb infos = 4;</code>
     */
    public Builder addInfos(com.exchange.proto.wallet.wallet.ReservationInfoPb value) {
      if (infosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInfosIsMutable();
        infos_.add(value);
        onChanged();
      } else {
        infosBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .wallet.ReservationInfoPb infos = 4;</code>
     */
    public Builder addInfos(
        int index, com.exchange.proto.wallet.wallet.ReservationInfoPb value) {
      if (infosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInfosIsMutable();
        infos_.add(index, value);
        onChanged();
      } else {
        infosBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .wallet.ReservationInfoPb infos = 4;</code>
     */
    public Builder addInfos(
        com.exchange.proto.wallet.wallet.ReservationInfoPb.Builder builderForValue) {
      if (infosBuilder_ == null) {
        ensureInfosIsMutable();
        infos_.add(builderForValue.build());
        onChanged();
      } else {
        infosBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .wallet.ReservationInfoPb infos = 4;</code>
     */
    public Builder addInfos(
        int index, com.exchange.proto.wallet.wallet.ReservationInfoPb.Builder builderForValue) {
      if (infosBuilder_ == null) {
        ensureInfosIsMutable();
        infos_.add(index, builderForValue.build());
        onChanged();
      } else {
        infosBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .wallet.ReservationInfoPb infos = 4;</code>
     */
    public Builder addAllInfos(
        java.lang.Iterable<? extends com.exchange.proto.wallet.wallet.ReservationInfoPb> values) {
      if (infosBuilder_ == null) {
        ensureInfosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, infos_);
        onChanged();
      } else {
        infosBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .wallet.ReservationInfoPb infos = 4;</code>
     */
    public Builder clearInfos() {
      if (infosBuilder_ == null) {
        infos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        infosBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .wallet.ReservationInfoPb infos = 4;</code>
     */
    public Builder removeInfos(int index) {
      if (infosBuilder_ == null) {
        ensureInfosIsMutable();
        infos_.remove(index);
        onChanged();
      } else {
        infosBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .wallet.ReservationInfoPb infos = 4;</code>
     */
    public com.exchange.proto.wallet.wallet.ReservationInfoPb.Builder getInfosBuilder(
        int index) {
      return getInfosFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .wallet.ReservationInfoPb infos = 4;</code>
     */
    public com.exchange.proto.wallet.wallet.ReservationInfoPbOrBuilder getInfosOrBuilder(
        int index) {
      if (infosBuilder_ == null) {
        return infos_.get(index);  } else {
        return infosBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .wallet.ReservationInfoPb infos = 4;</code>
     */
    public java.util.List<? extends com.exchange.proto.wallet.wallet.ReservationInfoPbOrBuilder> 
         getInfosOrBuilderList() {
      if (infosBuilder_ != null) {
        return infosBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(infos_);
      }
    }
    /**
     * <code>repeated .wallet.ReservationInfoPb infos = 4;</code>
     */
    public com.exchange.proto.wallet.wallet.ReservationInfoPb.Builder addInfosBuilder() {
      return getInfosFieldBuilder().addBuilder(
          com.exchange.proto.wallet.wallet.ReservationInfoPb.getDefaultInstance());
    }
    /**
     * <code>repeated .wallet.ReservationInfoPb infos = 4;</code>
     */
    public com.exchange.proto.wallet.wallet.ReservationInfoPb.Builder addInfosBuilder(
        int index) {
      return getInfosFieldBuilder().addBuilder(
          index, com.exchange.proto.wallet.wallet.ReservationInfoPb.getDefaultInstance());
    }
    /**
     * <code>repeated .wallet.ReservationInfoPb infos = 4;</code>
     */
    public java.util.List<com.exchange.proto.wallet.wallet.ReservationInfoPb.Builder> 
         getInfosBuilderList() {
      return getInfosFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.exchange.proto.wallet.wallet.ReservationInfoPb, com.exchange.proto.wallet.wallet.ReservationInfoPb.Builder, com.exchange.proto.wallet.wallet.ReservationInfoPbOrBuilder> 
        getInfosFieldBuilder() {
      if (infosBuilder_ == null) {
        infosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.exchange.proto.wallet.wallet.ReservationInfoPb, com.exchange.proto.wallet.wallet.ReservationInfoPb.Builder, com.exchange.proto.wallet.wallet.ReservationInfoPbOrBuilder>(
                infos_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        infos_ = null;
      }
      return infosBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:wallet.ReserveTransactionReplyPb)
  }

  // @@protoc_insertion_point(class_scope:wallet.ReserveTransactionReplyPb)
  private static final com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb();
  }

  public static com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReserveTransactionReplyPb>
      PARSER = new com.google.protobuf.AbstractParser<ReserveTransactionReplyPb>() {
    @java.lang.Override
    public ReserveTransactionReplyPb parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReserveTransactionReplyPb(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReserveTransactionReplyPb> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReserveTransactionReplyPb> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.exchange.proto.wallet.wallet.ReserveTransactionReplyPb getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

