// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet/wallet_transaction.proto

package com.exchange.proto.wallet.wallet;

/**
 * Protobuf type {@code wallet.ReservationInfoPb}
 */
public final class ReservationInfoPb extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:wallet.ReservationInfoPb)
    ReservationInfoPbOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReservationInfoPb.newBuilder() to construct.
  private ReservationInfoPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReservationInfoPb() {
    reservationRef_ = "";
    walletRef_ = "";
    assetCode_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ReservationInfoPb();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReservationInfoPb(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            reservationRef_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            walletRef_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            assetCode_ = s;
            break;
          }
          case 32: {

            amount_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.exchange.proto.wallet.wallet.WalletTransaction.internal_static_wallet_ReservationInfoPb_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.exchange.proto.wallet.wallet.WalletTransaction.internal_static_wallet_ReservationInfoPb_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.exchange.proto.wallet.wallet.ReservationInfoPb.class, com.exchange.proto.wallet.wallet.ReservationInfoPb.Builder.class);
  }

  public static final int RESERVATION_REF_FIELD_NUMBER = 1;
  private volatile java.lang.Object reservationRef_;
  /**
   * <code>string reservation_ref = 1;</code>
   * @return The reservationRef.
   */
  @java.lang.Override
  public java.lang.String getReservationRef() {
    java.lang.Object ref = reservationRef_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      reservationRef_ = s;
      return s;
    }
  }
  /**
   * <code>string reservation_ref = 1;</code>
   * @return The bytes for reservationRef.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReservationRefBytes() {
    java.lang.Object ref = reservationRef_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      reservationRef_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WALLET_REF_FIELD_NUMBER = 2;
  private volatile java.lang.Object walletRef_;
  /**
   * <code>string wallet_ref = 2;</code>
   * @return The walletRef.
   */
  @java.lang.Override
  public java.lang.String getWalletRef() {
    java.lang.Object ref = walletRef_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      walletRef_ = s;
      return s;
    }
  }
  /**
   * <code>string wallet_ref = 2;</code>
   * @return The bytes for walletRef.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWalletRefBytes() {
    java.lang.Object ref = walletRef_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      walletRef_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ASSET_CODE_FIELD_NUMBER = 3;
  private volatile java.lang.Object assetCode_;
  /**
   * <code>string asset_code = 3;</code>
   * @return The assetCode.
   */
  @java.lang.Override
  public java.lang.String getAssetCode() {
    java.lang.Object ref = assetCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      assetCode_ = s;
      return s;
    }
  }
  /**
   * <code>string asset_code = 3;</code>
   * @return The bytes for assetCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAssetCodeBytes() {
    java.lang.Object ref = assetCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      assetCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AMOUNT_FIELD_NUMBER = 4;
  private long amount_;
  /**
   * <code>int64 amount = 4;</code>
   * @return The amount.
   */
  @java.lang.Override
  public long getAmount() {
    return amount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getReservationRefBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, reservationRef_);
    }
    if (!getWalletRefBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, walletRef_);
    }
    if (!getAssetCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, assetCode_);
    }
    if (amount_ != 0L) {
      output.writeInt64(4, amount_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getReservationRefBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, reservationRef_);
    }
    if (!getWalletRefBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, walletRef_);
    }
    if (!getAssetCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, assetCode_);
    }
    if (amount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, amount_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.exchange.proto.wallet.wallet.ReservationInfoPb)) {
      return super.equals(obj);
    }
    com.exchange.proto.wallet.wallet.ReservationInfoPb other = (com.exchange.proto.wallet.wallet.ReservationInfoPb) obj;

    if (!getReservationRef()
        .equals(other.getReservationRef())) return false;
    if (!getWalletRef()
        .equals(other.getWalletRef())) return false;
    if (!getAssetCode()
        .equals(other.getAssetCode())) return false;
    if (getAmount()
        != other.getAmount()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESERVATION_REF_FIELD_NUMBER;
    hash = (53 * hash) + getReservationRef().hashCode();
    hash = (37 * hash) + WALLET_REF_FIELD_NUMBER;
    hash = (53 * hash) + getWalletRef().hashCode();
    hash = (37 * hash) + ASSET_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getAssetCode().hashCode();
    hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAmount());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.exchange.proto.wallet.wallet.ReservationInfoPb parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.exchange.proto.wallet.wallet.ReservationInfoPb parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.exchange.proto.wallet.wallet.ReservationInfoPb parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.exchange.proto.wallet.wallet.ReservationInfoPb parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.exchange.proto.wallet.wallet.ReservationInfoPb parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.exchange.proto.wallet.wallet.ReservationInfoPb parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.exchange.proto.wallet.wallet.ReservationInfoPb parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.exchange.proto.wallet.wallet.ReservationInfoPb parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.exchange.proto.wallet.wallet.ReservationInfoPb parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.exchange.proto.wallet.wallet.ReservationInfoPb parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.exchange.proto.wallet.wallet.ReservationInfoPb parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.exchange.proto.wallet.wallet.ReservationInfoPb parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.exchange.proto.wallet.wallet.ReservationInfoPb prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code wallet.ReservationInfoPb}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:wallet.ReservationInfoPb)
      com.exchange.proto.wallet.wallet.ReservationInfoPbOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.exchange.proto.wallet.wallet.WalletTransaction.internal_static_wallet_ReservationInfoPb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.exchange.proto.wallet.wallet.WalletTransaction.internal_static_wallet_ReservationInfoPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.exchange.proto.wallet.wallet.ReservationInfoPb.class, com.exchange.proto.wallet.wallet.ReservationInfoPb.Builder.class);
    }

    // Construct using com.exchange.proto.wallet.wallet.ReservationInfoPb.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      reservationRef_ = "";

      walletRef_ = "";

      assetCode_ = "";

      amount_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.exchange.proto.wallet.wallet.WalletTransaction.internal_static_wallet_ReservationInfoPb_descriptor;
    }

    @java.lang.Override
    public com.exchange.proto.wallet.wallet.ReservationInfoPb getDefaultInstanceForType() {
      return com.exchange.proto.wallet.wallet.ReservationInfoPb.getDefaultInstance();
    }

    @java.lang.Override
    public com.exchange.proto.wallet.wallet.ReservationInfoPb build() {
      com.exchange.proto.wallet.wallet.ReservationInfoPb result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.exchange.proto.wallet.wallet.ReservationInfoPb buildPartial() {
      com.exchange.proto.wallet.wallet.ReservationInfoPb result = new com.exchange.proto.wallet.wallet.ReservationInfoPb(this);
      result.reservationRef_ = reservationRef_;
      result.walletRef_ = walletRef_;
      result.assetCode_ = assetCode_;
      result.amount_ = amount_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.exchange.proto.wallet.wallet.ReservationInfoPb) {
        return mergeFrom((com.exchange.proto.wallet.wallet.ReservationInfoPb)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.exchange.proto.wallet.wallet.ReservationInfoPb other) {
      if (other == com.exchange.proto.wallet.wallet.ReservationInfoPb.getDefaultInstance()) return this;
      if (!other.getReservationRef().isEmpty()) {
        reservationRef_ = other.reservationRef_;
        onChanged();
      }
      if (!other.getWalletRef().isEmpty()) {
        walletRef_ = other.walletRef_;
        onChanged();
      }
      if (!other.getAssetCode().isEmpty()) {
        assetCode_ = other.assetCode_;
        onChanged();
      }
      if (other.getAmount() != 0L) {
        setAmount(other.getAmount());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.exchange.proto.wallet.wallet.ReservationInfoPb parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.exchange.proto.wallet.wallet.ReservationInfoPb) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object reservationRef_ = "";
    /**
     * <code>string reservation_ref = 1;</code>
     * @return The reservationRef.
     */
    public java.lang.String getReservationRef() {
      java.lang.Object ref = reservationRef_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reservationRef_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string reservation_ref = 1;</code>
     * @return The bytes for reservationRef.
     */
    public com.google.protobuf.ByteString
        getReservationRefBytes() {
      java.lang.Object ref = reservationRef_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reservationRef_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string reservation_ref = 1;</code>
     * @param value The reservationRef to set.
     * @return This builder for chaining.
     */
    public Builder setReservationRef(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      reservationRef_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string reservation_ref = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReservationRef() {
      
      reservationRef_ = getDefaultInstance().getReservationRef();
      onChanged();
      return this;
    }
    /**
     * <code>string reservation_ref = 1;</code>
     * @param value The bytes for reservationRef to set.
     * @return This builder for chaining.
     */
    public Builder setReservationRefBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      reservationRef_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object walletRef_ = "";
    /**
     * <code>string wallet_ref = 2;</code>
     * @return The walletRef.
     */
    public java.lang.String getWalletRef() {
      java.lang.Object ref = walletRef_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        walletRef_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string wallet_ref = 2;</code>
     * @return The bytes for walletRef.
     */
    public com.google.protobuf.ByteString
        getWalletRefBytes() {
      java.lang.Object ref = walletRef_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        walletRef_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string wallet_ref = 2;</code>
     * @param value The walletRef to set.
     * @return This builder for chaining.
     */
    public Builder setWalletRef(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      walletRef_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string wallet_ref = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearWalletRef() {
      
      walletRef_ = getDefaultInstance().getWalletRef();
      onChanged();
      return this;
    }
    /**
     * <code>string wallet_ref = 2;</code>
     * @param value The bytes for walletRef to set.
     * @return This builder for chaining.
     */
    public Builder setWalletRefBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      walletRef_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object assetCode_ = "";
    /**
     * <code>string asset_code = 3;</code>
     * @return The assetCode.
     */
    public java.lang.String getAssetCode() {
      java.lang.Object ref = assetCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        assetCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string asset_code = 3;</code>
     * @return The bytes for assetCode.
     */
    public com.google.protobuf.ByteString
        getAssetCodeBytes() {
      java.lang.Object ref = assetCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        assetCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string asset_code = 3;</code>
     * @param value The assetCode to set.
     * @return This builder for chaining.
     */
    public Builder setAssetCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      assetCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string asset_code = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAssetCode() {
      
      assetCode_ = getDefaultInstance().getAssetCode();
      onChanged();
      return this;
    }
    /**
     * <code>string asset_code = 3;</code>
     * @param value The bytes for assetCode to set.
     * @return This builder for chaining.
     */
    public Builder setAssetCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      assetCode_ = value;
      onChanged();
      return this;
    }

    private long amount_ ;
    /**
     * <code>int64 amount = 4;</code>
     * @return The amount.
     */
    @java.lang.Override
    public long getAmount() {
      return amount_;
    }
    /**
     * <code>int64 amount = 4;</code>
     * @param value The amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmount(long value) {
      
      amount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 amount = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAmount() {
      
      amount_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:wallet.ReservationInfoPb)
  }

  // @@protoc_insertion_point(class_scope:wallet.ReservationInfoPb)
  private static final com.exchange.proto.wallet.wallet.ReservationInfoPb DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.exchange.proto.wallet.wallet.ReservationInfoPb();
  }

  public static com.exchange.proto.wallet.wallet.ReservationInfoPb getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReservationInfoPb>
      PARSER = new com.google.protobuf.AbstractParser<ReservationInfoPb>() {
    @java.lang.Override
    public ReservationInfoPb parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReservationInfoPb(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReservationInfoPb> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReservationInfoPb> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.exchange.proto.wallet.wallet.ReservationInfoPb getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

