// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet/wallet_transaction.proto

package com.exchange.proto.wallet.wallet;

public interface ReserveTransactionRequestPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wallet.ReserveTransactionRequestPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reference_id = 1;</code>
   * @return The referenceId.
   */
  java.lang.String getReferenceId();
  /**
   * <code>string reference_id = 1;</code>
   * @return The bytes for referenceId.
   */
  com.google.protobuf.ByteString
      getReferenceIdBytes();

  /**
   * <code>.wallet.ServiceIdPb initiator = 2;</code>
   * @return The enum numeric value on the wire for initiator.
   */
  int getInitiatorValue();
  /**
   * <code>.wallet.ServiceIdPb initiator = 2;</code>
   * @return The initiator.
   */
  com.exchange.proto.wallet.common.ServiceIdPb getInitiator();

  /**
   * <code>string idempotency_key = 3;</code>
   * @return The idempotencyKey.
   */
  java.lang.String getIdempotencyKey();
  /**
   * <code>string idempotency_key = 3;</code>
   * @return The bytes for idempotencyKey.
   */
  com.google.protobuf.ByteString
      getIdempotencyKeyBytes();

  /**
   * <code>.wallet.BusinessTypePb business_type = 4;</code>
   * @return The enum numeric value on the wire for businessType.
   */
  int getBusinessTypeValue();
  /**
   * <code>.wallet.BusinessTypePb business_type = 4;</code>
   * @return The businessType.
   */
  com.exchange.proto.wallet.common.BusinessTypePb getBusinessType();

  /**
   * <code>repeated .wallet.TransactionLinePb lines = 5;</code>
   */
  java.util.List<com.exchange.proto.wallet.wallet.TransactionLinePb> 
      getLinesList();
  /**
   * <code>repeated .wallet.TransactionLinePb lines = 5;</code>
   */
  com.exchange.proto.wallet.wallet.TransactionLinePb getLines(int index);
  /**
   * <code>repeated .wallet.TransactionLinePb lines = 5;</code>
   */
  int getLinesCount();
  /**
   * <code>repeated .wallet.TransactionLinePb lines = 5;</code>
   */
  java.util.List<? extends com.exchange.proto.wallet.wallet.TransactionLinePbOrBuilder> 
      getLinesOrBuilderList();
  /**
   * <code>repeated .wallet.TransactionLinePb lines = 5;</code>
   */
  com.exchange.proto.wallet.wallet.TransactionLinePbOrBuilder getLinesOrBuilder(
      int index);
}
