// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet/wallet_transaction.proto

package com.exchange.proto.wallet.wallet;

public interface TransactionLinePbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wallet.TransactionLinePb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string wallet_ref = 1;</code>
   * @return The walletRef.
   */
  java.lang.String getWalletRef();
  /**
   * <code>string wallet_ref = 1;</code>
   * @return The bytes for walletRef.
   */
  com.google.protobuf.ByteString
      getWalletRefBytes();

  /**
   * <code>string asset_code = 2;</code>
   * @return The assetCode.
   */
  java.lang.String getAssetCode();
  /**
   * <code>string asset_code = 2;</code>
   * @return The bytes for assetCode.
   */
  com.google.protobuf.ByteString
      getAssetCodeBytes();

  /**
   * <code>.wallet.OperationTypePb operation_type = 3;</code>
   * @return The enum numeric value on the wire for operationType.
   */
  int getOperationTypeValue();
  /**
   * <code>.wallet.OperationTypePb operation_type = 3;</code>
   * @return The operationType.
   */
  com.exchange.proto.wallet.common.OperationTypePb getOperationType();

  /**
   * <code>int64 amount = 4;</code>
   * @return The amount.
   */
  long getAmount();

  /**
   * <pre>
   * used in 2-step transaction, when action_type=consume/release
   * </pre>
   *
   * <code>string reservation_ref = 5;</code>
   * @return The reservationRef.
   */
  java.lang.String getReservationRef();
  /**
   * <pre>
   * used in 2-step transaction, when action_type=consume/release
   * </pre>
   *
   * <code>string reservation_ref = 5;</code>
   * @return The bytes for reservationRef.
   */
  com.google.protobuf.ByteString
      getReservationRefBytes();
}
