// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet/wallet_transaction.proto

package com.exchange.proto.wallet.wallet;

public interface TransactionLinePbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wallet.TransactionLinePb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string wallet_ref = 1;</code>
   * @return The walletRef.
   */
  java.lang.String getWalletRef();
  /**
   * <code>string wallet_ref = 1;</code>
   * @return The bytes for walletRef.
   */
  com.google.protobuf.ByteString
      getWalletRefBytes();

  /**
   * <code>string asset_code = 2;</code>
   * @return The assetCode.
   */
  java.lang.String getAssetCode();
  /**
   * <code>string asset_code = 2;</code>
   * @return The bytes for assetCode.
   */
  com.google.protobuf.ByteString
      getAssetCodeBytes();

  /**
   * <code>.wallet.ActionTypePb action_type = 3;</code>
   * @return The enum numeric value on the wire for actionType.
   */
  int getActionTypeValue();
  /**
   * <code>.wallet.ActionTypePb action_type = 3;</code>
   * @return The actionType.
   */
  com.exchange.proto.wallet.common.ActionTypePb getActionType();

  /**
   * <code>int64 amount = 4;</code>
   * @return The amount.
   */
  long getAmount();
}
