// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet/wallet_transaction.proto

package com.exchange.proto.wallet.wallet;

/**
 * Protobuf type {@code wallet.TwoStepTransactionRequestPb}
 */
public final class TwoStepTransactionRequestPb extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:wallet.TwoStepTransactionRequestPb)
    TwoStepTransactionRequestPbOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TwoStepTransactionRequestPb.newBuilder() to construct.
  private TwoStepTransactionRequestPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TwoStepTransactionRequestPb() {
    referenceId_ = "";
    initiator_ = 0;
    idempotencyKey_ = "";
    businessType_ = 0;
    lines_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TwoStepTransactionRequestPb();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TwoStepTransactionRequestPb(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            referenceId_ = s;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            initiator_ = rawValue;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            idempotencyKey_ = s;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            businessType_ = rawValue;
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              lines_ = new java.util.ArrayList<com.exchange.proto.wallet.wallet.TransactionLinePb>();
              mutable_bitField0_ |= 0x00000001;
            }
            lines_.add(
                input.readMessage(com.exchange.proto.wallet.wallet.TransactionLinePb.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        lines_ = java.util.Collections.unmodifiableList(lines_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.exchange.proto.wallet.wallet.WalletTransaction.internal_static_wallet_TwoStepTransactionRequestPb_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.exchange.proto.wallet.wallet.WalletTransaction.internal_static_wallet_TwoStepTransactionRequestPb_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb.class, com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb.Builder.class);
  }

  public static final int REFERENCE_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object referenceId_;
  /**
   * <code>string reference_id = 1;</code>
   * @return The referenceId.
   */
  @java.lang.Override
  public java.lang.String getReferenceId() {
    java.lang.Object ref = referenceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      referenceId_ = s;
      return s;
    }
  }
  /**
   * <code>string reference_id = 1;</code>
   * @return The bytes for referenceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReferenceIdBytes() {
    java.lang.Object ref = referenceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      referenceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INITIATOR_FIELD_NUMBER = 2;
  private int initiator_;
  /**
   * <code>.wallet.ServiceIdPb initiator = 2;</code>
   * @return The enum numeric value on the wire for initiator.
   */
  @java.lang.Override public int getInitiatorValue() {
    return initiator_;
  }
  /**
   * <code>.wallet.ServiceIdPb initiator = 2;</code>
   * @return The initiator.
   */
  @java.lang.Override public com.exchange.proto.wallet.common.ServiceIdPb getInitiator() {
    @SuppressWarnings("deprecation")
    com.exchange.proto.wallet.common.ServiceIdPb result = com.exchange.proto.wallet.common.ServiceIdPb.valueOf(initiator_);
    return result == null ? com.exchange.proto.wallet.common.ServiceIdPb.UNRECOGNIZED : result;
  }

  public static final int IDEMPOTENCY_KEY_FIELD_NUMBER = 3;
  private volatile java.lang.Object idempotencyKey_;
  /**
   * <code>string idempotency_key = 3;</code>
   * @return The idempotencyKey.
   */
  @java.lang.Override
  public java.lang.String getIdempotencyKey() {
    java.lang.Object ref = idempotencyKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      idempotencyKey_ = s;
      return s;
    }
  }
  /**
   * <code>string idempotency_key = 3;</code>
   * @return The bytes for idempotencyKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdempotencyKeyBytes() {
    java.lang.Object ref = idempotencyKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      idempotencyKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BUSINESS_TYPE_FIELD_NUMBER = 4;
  private int businessType_;
  /**
   * <code>.wallet.BusinessTypePb business_type = 4;</code>
   * @return The enum numeric value on the wire for businessType.
   */
  @java.lang.Override public int getBusinessTypeValue() {
    return businessType_;
  }
  /**
   * <code>.wallet.BusinessTypePb business_type = 4;</code>
   * @return The businessType.
   */
  @java.lang.Override public com.exchange.proto.wallet.common.BusinessTypePb getBusinessType() {
    @SuppressWarnings("deprecation")
    com.exchange.proto.wallet.common.BusinessTypePb result = com.exchange.proto.wallet.common.BusinessTypePb.valueOf(businessType_);
    return result == null ? com.exchange.proto.wallet.common.BusinessTypePb.UNRECOGNIZED : result;
  }

  public static final int LINES_FIELD_NUMBER = 5;
  private java.util.List<com.exchange.proto.wallet.wallet.TransactionLinePb> lines_;
  /**
   * <code>repeated .wallet.TransactionLinePb lines = 5;</code>
   */
  @java.lang.Override
  public java.util.List<com.exchange.proto.wallet.wallet.TransactionLinePb> getLinesList() {
    return lines_;
  }
  /**
   * <code>repeated .wallet.TransactionLinePb lines = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.exchange.proto.wallet.wallet.TransactionLinePbOrBuilder> 
      getLinesOrBuilderList() {
    return lines_;
  }
  /**
   * <code>repeated .wallet.TransactionLinePb lines = 5;</code>
   */
  @java.lang.Override
  public int getLinesCount() {
    return lines_.size();
  }
  /**
   * <code>repeated .wallet.TransactionLinePb lines = 5;</code>
   */
  @java.lang.Override
  public com.exchange.proto.wallet.wallet.TransactionLinePb getLines(int index) {
    return lines_.get(index);
  }
  /**
   * <code>repeated .wallet.TransactionLinePb lines = 5;</code>
   */
  @java.lang.Override
  public com.exchange.proto.wallet.wallet.TransactionLinePbOrBuilder getLinesOrBuilder(
      int index) {
    return lines_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getReferenceIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, referenceId_);
    }
    if (initiator_ != com.exchange.proto.wallet.common.ServiceIdPb.ServiceIdPb_Unknown.getNumber()) {
      output.writeEnum(2, initiator_);
    }
    if (!getIdempotencyKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, idempotencyKey_);
    }
    if (businessType_ != com.exchange.proto.wallet.common.BusinessTypePb.BusinessTypePb_Unknown.getNumber()) {
      output.writeEnum(4, businessType_);
    }
    for (int i = 0; i < lines_.size(); i++) {
      output.writeMessage(5, lines_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getReferenceIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, referenceId_);
    }
    if (initiator_ != com.exchange.proto.wallet.common.ServiceIdPb.ServiceIdPb_Unknown.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, initiator_);
    }
    if (!getIdempotencyKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, idempotencyKey_);
    }
    if (businessType_ != com.exchange.proto.wallet.common.BusinessTypePb.BusinessTypePb_Unknown.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, businessType_);
    }
    for (int i = 0; i < lines_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, lines_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb)) {
      return super.equals(obj);
    }
    com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb other = (com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb) obj;

    if (!getReferenceId()
        .equals(other.getReferenceId())) return false;
    if (initiator_ != other.initiator_) return false;
    if (!getIdempotencyKey()
        .equals(other.getIdempotencyKey())) return false;
    if (businessType_ != other.businessType_) return false;
    if (!getLinesList()
        .equals(other.getLinesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REFERENCE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getReferenceId().hashCode();
    hash = (37 * hash) + INITIATOR_FIELD_NUMBER;
    hash = (53 * hash) + initiator_;
    hash = (37 * hash) + IDEMPOTENCY_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getIdempotencyKey().hashCode();
    hash = (37 * hash) + BUSINESS_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + businessType_;
    if (getLinesCount() > 0) {
      hash = (37 * hash) + LINES_FIELD_NUMBER;
      hash = (53 * hash) + getLinesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code wallet.TwoStepTransactionRequestPb}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:wallet.TwoStepTransactionRequestPb)
      com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPbOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.exchange.proto.wallet.wallet.WalletTransaction.internal_static_wallet_TwoStepTransactionRequestPb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.exchange.proto.wallet.wallet.WalletTransaction.internal_static_wallet_TwoStepTransactionRequestPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb.class, com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb.Builder.class);
    }

    // Construct using com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getLinesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      referenceId_ = "";

      initiator_ = 0;

      idempotencyKey_ = "";

      businessType_ = 0;

      if (linesBuilder_ == null) {
        lines_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        linesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.exchange.proto.wallet.wallet.WalletTransaction.internal_static_wallet_TwoStepTransactionRequestPb_descriptor;
    }

    @java.lang.Override
    public com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb getDefaultInstanceForType() {
      return com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb.getDefaultInstance();
    }

    @java.lang.Override
    public com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb build() {
      com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb buildPartial() {
      com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb result = new com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb(this);
      int from_bitField0_ = bitField0_;
      result.referenceId_ = referenceId_;
      result.initiator_ = initiator_;
      result.idempotencyKey_ = idempotencyKey_;
      result.businessType_ = businessType_;
      if (linesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          lines_ = java.util.Collections.unmodifiableList(lines_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.lines_ = lines_;
      } else {
        result.lines_ = linesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb) {
        return mergeFrom((com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb other) {
      if (other == com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb.getDefaultInstance()) return this;
      if (!other.getReferenceId().isEmpty()) {
        referenceId_ = other.referenceId_;
        onChanged();
      }
      if (other.initiator_ != 0) {
        setInitiatorValue(other.getInitiatorValue());
      }
      if (!other.getIdempotencyKey().isEmpty()) {
        idempotencyKey_ = other.idempotencyKey_;
        onChanged();
      }
      if (other.businessType_ != 0) {
        setBusinessTypeValue(other.getBusinessTypeValue());
      }
      if (linesBuilder_ == null) {
        if (!other.lines_.isEmpty()) {
          if (lines_.isEmpty()) {
            lines_ = other.lines_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureLinesIsMutable();
            lines_.addAll(other.lines_);
          }
          onChanged();
        }
      } else {
        if (!other.lines_.isEmpty()) {
          if (linesBuilder_.isEmpty()) {
            linesBuilder_.dispose();
            linesBuilder_ = null;
            lines_ = other.lines_;
            bitField0_ = (bitField0_ & ~0x00000001);
            linesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getLinesFieldBuilder() : null;
          } else {
            linesBuilder_.addAllMessages(other.lines_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object referenceId_ = "";
    /**
     * <code>string reference_id = 1;</code>
     * @return The referenceId.
     */
    public java.lang.String getReferenceId() {
      java.lang.Object ref = referenceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        referenceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string reference_id = 1;</code>
     * @return The bytes for referenceId.
     */
    public com.google.protobuf.ByteString
        getReferenceIdBytes() {
      java.lang.Object ref = referenceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        referenceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string reference_id = 1;</code>
     * @param value The referenceId to set.
     * @return This builder for chaining.
     */
    public Builder setReferenceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      referenceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string reference_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReferenceId() {
      
      referenceId_ = getDefaultInstance().getReferenceId();
      onChanged();
      return this;
    }
    /**
     * <code>string reference_id = 1;</code>
     * @param value The bytes for referenceId to set.
     * @return This builder for chaining.
     */
    public Builder setReferenceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      referenceId_ = value;
      onChanged();
      return this;
    }

    private int initiator_ = 0;
    /**
     * <code>.wallet.ServiceIdPb initiator = 2;</code>
     * @return The enum numeric value on the wire for initiator.
     */
    @java.lang.Override public int getInitiatorValue() {
      return initiator_;
    }
    /**
     * <code>.wallet.ServiceIdPb initiator = 2;</code>
     * @param value The enum numeric value on the wire for initiator to set.
     * @return This builder for chaining.
     */
    public Builder setInitiatorValue(int value) {
      
      initiator_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.wallet.ServiceIdPb initiator = 2;</code>
     * @return The initiator.
     */
    @java.lang.Override
    public com.exchange.proto.wallet.common.ServiceIdPb getInitiator() {
      @SuppressWarnings("deprecation")
      com.exchange.proto.wallet.common.ServiceIdPb result = com.exchange.proto.wallet.common.ServiceIdPb.valueOf(initiator_);
      return result == null ? com.exchange.proto.wallet.common.ServiceIdPb.UNRECOGNIZED : result;
    }
    /**
     * <code>.wallet.ServiceIdPb initiator = 2;</code>
     * @param value The initiator to set.
     * @return This builder for chaining.
     */
    public Builder setInitiator(com.exchange.proto.wallet.common.ServiceIdPb value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      initiator_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.wallet.ServiceIdPb initiator = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearInitiator() {
      
      initiator_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object idempotencyKey_ = "";
    /**
     * <code>string idempotency_key = 3;</code>
     * @return The idempotencyKey.
     */
    public java.lang.String getIdempotencyKey() {
      java.lang.Object ref = idempotencyKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idempotencyKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string idempotency_key = 3;</code>
     * @return The bytes for idempotencyKey.
     */
    public com.google.protobuf.ByteString
        getIdempotencyKeyBytes() {
      java.lang.Object ref = idempotencyKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idempotencyKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string idempotency_key = 3;</code>
     * @param value The idempotencyKey to set.
     * @return This builder for chaining.
     */
    public Builder setIdempotencyKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      idempotencyKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string idempotency_key = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdempotencyKey() {
      
      idempotencyKey_ = getDefaultInstance().getIdempotencyKey();
      onChanged();
      return this;
    }
    /**
     * <code>string idempotency_key = 3;</code>
     * @param value The bytes for idempotencyKey to set.
     * @return This builder for chaining.
     */
    public Builder setIdempotencyKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      idempotencyKey_ = value;
      onChanged();
      return this;
    }

    private int businessType_ = 0;
    /**
     * <code>.wallet.BusinessTypePb business_type = 4;</code>
     * @return The enum numeric value on the wire for businessType.
     */
    @java.lang.Override public int getBusinessTypeValue() {
      return businessType_;
    }
    /**
     * <code>.wallet.BusinessTypePb business_type = 4;</code>
     * @param value The enum numeric value on the wire for businessType to set.
     * @return This builder for chaining.
     */
    public Builder setBusinessTypeValue(int value) {
      
      businessType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.wallet.BusinessTypePb business_type = 4;</code>
     * @return The businessType.
     */
    @java.lang.Override
    public com.exchange.proto.wallet.common.BusinessTypePb getBusinessType() {
      @SuppressWarnings("deprecation")
      com.exchange.proto.wallet.common.BusinessTypePb result = com.exchange.proto.wallet.common.BusinessTypePb.valueOf(businessType_);
      return result == null ? com.exchange.proto.wallet.common.BusinessTypePb.UNRECOGNIZED : result;
    }
    /**
     * <code>.wallet.BusinessTypePb business_type = 4;</code>
     * @param value The businessType to set.
     * @return This builder for chaining.
     */
    public Builder setBusinessType(com.exchange.proto.wallet.common.BusinessTypePb value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      businessType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.wallet.BusinessTypePb business_type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBusinessType() {
      
      businessType_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.exchange.proto.wallet.wallet.TransactionLinePb> lines_ =
      java.util.Collections.emptyList();
    private void ensureLinesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        lines_ = new java.util.ArrayList<com.exchange.proto.wallet.wallet.TransactionLinePb>(lines_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.exchange.proto.wallet.wallet.TransactionLinePb, com.exchange.proto.wallet.wallet.TransactionLinePb.Builder, com.exchange.proto.wallet.wallet.TransactionLinePbOrBuilder> linesBuilder_;

    /**
     * <code>repeated .wallet.TransactionLinePb lines = 5;</code>
     */
    public java.util.List<com.exchange.proto.wallet.wallet.TransactionLinePb> getLinesList() {
      if (linesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(lines_);
      } else {
        return linesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .wallet.TransactionLinePb lines = 5;</code>
     */
    public int getLinesCount() {
      if (linesBuilder_ == null) {
        return lines_.size();
      } else {
        return linesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .wallet.TransactionLinePb lines = 5;</code>
     */
    public com.exchange.proto.wallet.wallet.TransactionLinePb getLines(int index) {
      if (linesBuilder_ == null) {
        return lines_.get(index);
      } else {
        return linesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .wallet.TransactionLinePb lines = 5;</code>
     */
    public Builder setLines(
        int index, com.exchange.proto.wallet.wallet.TransactionLinePb value) {
      if (linesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLinesIsMutable();
        lines_.set(index, value);
        onChanged();
      } else {
        linesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .wallet.TransactionLinePb lines = 5;</code>
     */
    public Builder setLines(
        int index, com.exchange.proto.wallet.wallet.TransactionLinePb.Builder builderForValue) {
      if (linesBuilder_ == null) {
        ensureLinesIsMutable();
        lines_.set(index, builderForValue.build());
        onChanged();
      } else {
        linesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .wallet.TransactionLinePb lines = 5;</code>
     */
    public Builder addLines(com.exchange.proto.wallet.wallet.TransactionLinePb value) {
      if (linesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLinesIsMutable();
        lines_.add(value);
        onChanged();
      } else {
        linesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .wallet.TransactionLinePb lines = 5;</code>
     */
    public Builder addLines(
        int index, com.exchange.proto.wallet.wallet.TransactionLinePb value) {
      if (linesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLinesIsMutable();
        lines_.add(index, value);
        onChanged();
      } else {
        linesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .wallet.TransactionLinePb lines = 5;</code>
     */
    public Builder addLines(
        com.exchange.proto.wallet.wallet.TransactionLinePb.Builder builderForValue) {
      if (linesBuilder_ == null) {
        ensureLinesIsMutable();
        lines_.add(builderForValue.build());
        onChanged();
      } else {
        linesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .wallet.TransactionLinePb lines = 5;</code>
     */
    public Builder addLines(
        int index, com.exchange.proto.wallet.wallet.TransactionLinePb.Builder builderForValue) {
      if (linesBuilder_ == null) {
        ensureLinesIsMutable();
        lines_.add(index, builderForValue.build());
        onChanged();
      } else {
        linesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .wallet.TransactionLinePb lines = 5;</code>
     */
    public Builder addAllLines(
        java.lang.Iterable<? extends com.exchange.proto.wallet.wallet.TransactionLinePb> values) {
      if (linesBuilder_ == null) {
        ensureLinesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, lines_);
        onChanged();
      } else {
        linesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .wallet.TransactionLinePb lines = 5;</code>
     */
    public Builder clearLines() {
      if (linesBuilder_ == null) {
        lines_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        linesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .wallet.TransactionLinePb lines = 5;</code>
     */
    public Builder removeLines(int index) {
      if (linesBuilder_ == null) {
        ensureLinesIsMutable();
        lines_.remove(index);
        onChanged();
      } else {
        linesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .wallet.TransactionLinePb lines = 5;</code>
     */
    public com.exchange.proto.wallet.wallet.TransactionLinePb.Builder getLinesBuilder(
        int index) {
      return getLinesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .wallet.TransactionLinePb lines = 5;</code>
     */
    public com.exchange.proto.wallet.wallet.TransactionLinePbOrBuilder getLinesOrBuilder(
        int index) {
      if (linesBuilder_ == null) {
        return lines_.get(index);  } else {
        return linesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .wallet.TransactionLinePb lines = 5;</code>
     */
    public java.util.List<? extends com.exchange.proto.wallet.wallet.TransactionLinePbOrBuilder> 
         getLinesOrBuilderList() {
      if (linesBuilder_ != null) {
        return linesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(lines_);
      }
    }
    /**
     * <code>repeated .wallet.TransactionLinePb lines = 5;</code>
     */
    public com.exchange.proto.wallet.wallet.TransactionLinePb.Builder addLinesBuilder() {
      return getLinesFieldBuilder().addBuilder(
          com.exchange.proto.wallet.wallet.TransactionLinePb.getDefaultInstance());
    }
    /**
     * <code>repeated .wallet.TransactionLinePb lines = 5;</code>
     */
    public com.exchange.proto.wallet.wallet.TransactionLinePb.Builder addLinesBuilder(
        int index) {
      return getLinesFieldBuilder().addBuilder(
          index, com.exchange.proto.wallet.wallet.TransactionLinePb.getDefaultInstance());
    }
    /**
     * <code>repeated .wallet.TransactionLinePb lines = 5;</code>
     */
    public java.util.List<com.exchange.proto.wallet.wallet.TransactionLinePb.Builder> 
         getLinesBuilderList() {
      return getLinesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.exchange.proto.wallet.wallet.TransactionLinePb, com.exchange.proto.wallet.wallet.TransactionLinePb.Builder, com.exchange.proto.wallet.wallet.TransactionLinePbOrBuilder> 
        getLinesFieldBuilder() {
      if (linesBuilder_ == null) {
        linesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.exchange.proto.wallet.wallet.TransactionLinePb, com.exchange.proto.wallet.wallet.TransactionLinePb.Builder, com.exchange.proto.wallet.wallet.TransactionLinePbOrBuilder>(
                lines_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        lines_ = null;
      }
      return linesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:wallet.TwoStepTransactionRequestPb)
  }

  // @@protoc_insertion_point(class_scope:wallet.TwoStepTransactionRequestPb)
  private static final com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb();
  }

  public static com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TwoStepTransactionRequestPb>
      PARSER = new com.google.protobuf.AbstractParser<TwoStepTransactionRequestPb>() {
    @java.lang.Override
    public TwoStepTransactionRequestPb parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TwoStepTransactionRequestPb(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TwoStepTransactionRequestPb> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TwoStepTransactionRequestPb> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.exchange.proto.wallet.wallet.TwoStepTransactionRequestPb getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

