// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet/wallet_transaction.proto

package com.exchange.proto.wallet.wallet;

public interface TwoStepTransactionReplyPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wallet.TwoStepTransactionReplyPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.common.ErrorPb error = 1;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.common.ErrorPb error = 1;</code>
   * @return The error.
   */
  com.exchange.proto.common.error.ErrorPb getError();
  /**
   * <code>.common.ErrorPb error = 1;</code>
   */
  com.exchange.proto.common.error.ErrorPbOrBuilder getErrorOrBuilder();

  /**
   * <code>string transaction_id = 2;</code>
   * @return The transactionId.
   */
  java.lang.String getTransactionId();
  /**
   * <code>string transaction_id = 2;</code>
   * @return The bytes for transactionId.
   */
  com.google.protobuf.ByteString
      getTransactionIdBytes();

  /**
   * <code>.wallet.TransactionStatusPb status = 3;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.wallet.TransactionStatusPb status = 3;</code>
   * @return The status.
   */
  com.exchange.proto.wallet.common.TransactionStatusPb getStatus();
}
