// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet/wallet_service.proto

package com.exchange.proto.wallet.wallet;

public final class WalletServiceOuterClass {
  private WalletServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033wallet/wallet_service.proto\022\006wallet\032\032w" +
      "allet/create_wallet.proto\032\037wallet/wallet" +
      "_transaction.proto2\226\002\n\rWalletService\022L\n\014" +
      "createWallet\022\035.wallet.CreateWalletReques" +
      "tPb\032\033.wallet.CreateWalletReplyPb\"\000\022Y\n\021at" +
      "omicTransaction\022\".wallet.AtomicTransacti" +
      "onRequestPb\032 .wallet.AtomicTransactionRe" +
      "plyPb\022\\\n\022reserveTransaction\022#.wallet.Res" +
      "erveTransactionRequestPb\032!.wallet.Reserv" +
      "eTransactionReplyPbB$\n com.exchange.prot" +
      "o.wallet.walletP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.exchange.proto.wallet.wallet.CreateWallet.getDescriptor(),
          com.exchange.proto.wallet.wallet.WalletTransaction.getDescriptor(),
        });
    com.exchange.proto.wallet.wallet.CreateWallet.getDescriptor();
    com.exchange.proto.wallet.wallet.WalletTransaction.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
