// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet/wallet_transaction.proto

package com.exchange.proto.wallet.wallet;

public final class WalletTransaction {
  private WalletTransaction() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_AtomicTransactionRequestPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wallet_AtomicTransactionRequestPb_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_AtomicTransactionReplyPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wallet_AtomicTransactionReplyPb_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_TransactionLinePb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wallet_TransactionLinePb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037wallet/wallet_transaction.proto\022\006walle" +
      "t\032\030wallet/wallet_enum.proto\032%com/exchang" +
      "e/proto/common/error.proto\"\314\001\n\032AtomicTra" +
      "nsactionRequestPb\022\024\n\014reference_id\030\001 \001(\t\022" +
      "&\n\tinitiator\030\002 \001(\0162\023.wallet.ServiceIdPb\022" +
      "\027\n\017idempotency_key\030\003 \001(\t\022-\n\rbusiness_typ" +
      "e\030\004 \001(\0162\026.wallet.BusinessTypePb\022(\n\005lines" +
      "\030\005 \003(\0132\031.wallet.TransactionLinePb\"\177\n\030Ato" +
      "micTransactionReplyPb\022\036\n\005error\030\001 \001(\0132\017.c" +
      "ommon.ErrorPb\022\026\n\016transaction_id\030\002 \001(\t\022+\n" +
      "\006status\030\003 \001(\0162\033.wallet.TransactionStatus" +
      "Pb\"v\n\021TransactionLinePb\022\022\n\nwallet_ref\030\001 " +
      "\001(\t\022\022\n\nasset_code\030\002 \001(\t\022)\n\013action_type\030\003" +
      " \001(\0162\024.wallet.ActionTypePb\022\016\n\006amount\030\004 \001" +
      "(\003B$\n com.exchange.proto.wallet.walletP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.exchange.proto.wallet.common.WalletEnum.getDescriptor(),
          com.exchange.proto.common.error.Error.getDescriptor(),
        });
    internal_static_wallet_AtomicTransactionRequestPb_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_wallet_AtomicTransactionRequestPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wallet_AtomicTransactionRequestPb_descriptor,
        new java.lang.String[] { "ReferenceId", "Initiator", "IdempotencyKey", "BusinessType", "Lines", });
    internal_static_wallet_AtomicTransactionReplyPb_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_wallet_AtomicTransactionReplyPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wallet_AtomicTransactionReplyPb_descriptor,
        new java.lang.String[] { "Error", "TransactionId", "Status", });
    internal_static_wallet_TransactionLinePb_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_wallet_TransactionLinePb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wallet_TransactionLinePb_descriptor,
        new java.lang.String[] { "WalletRef", "AssetCode", "ActionType", "Amount", });
    com.exchange.proto.wallet.common.WalletEnum.getDescriptor();
    com.exchange.proto.common.error.Error.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
