// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet/wallet_service.proto

package com.exchange.proto.wallet.wallet;

public final class WalletServiceOuterClass {
  private WalletServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033wallet/wallet_service.proto\022\006wallet\032\032w" +
      "allet/create_wallet.proto2]\n\rWalletServi" +
      "ce\022L\n\014createWallet\022\035.wallet.CreateWallet" +
      "RequestPb\032\033.wallet.CreateWalletReplyPb\"\000" +
      "B$\n com.exchange.proto.wallet.walletP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.exchange.proto.wallet.wallet.CreateWallet.getDescriptor(),
        });
    com.exchange.proto.wallet.wallet.CreateWallet.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
