server:
  port: 10020

grpc:
  client:
    GLOBAL:
      enable-keep-alive: true
      negotiation-type: plaintext
    wallet-client:
      address: static://127.0.0.1:9092

spring:
  kafka:
    bootstrap-servers: 192.168.52.100:9092
    consumer:
      auto-offset-reset: latest
#  redis:
#    host: 192.168.10.172
#    port: 6379
#
#    redisson:
#      file: classpath:redisson.yaml
#      # OR (alternative) config: "singleServerConfig: ... (a long YAML string)"
