syntax = "proto3";

package ledger;

option java_multiple_files = true;
option java_package = "com.exchange.proto.ledger.account";

import "ledger/ledger_common.proto";

service AccountService {
  rpc createAccount(CreateAccountRequestPb) returns (CreateAccountReplyPb) {}
}

message CreateAccountRequestPb {
  string reference_id = 1;
  ServiceIdPb service_id = 2;
  string asset_id = 3;
  AccountCategoryPb category = 4;
  NormalSidePb normal_side = 5;
  OwnerTypePb owner_type = 6;
  string owner_id = 7;
}

message CreateAccountReplyPb {
  int32 code = 1;
  string msg = 2;
}
