spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/trade_walletservice?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false"
    username: root
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver

  cache:
    type: redis
  redis:
    host: 34.229.174.30
    port: 6379

  kafka:
    bootstrap-servers: 34.229.174.30:19092

    consumer:
      auto-offset-reset: latest
      fetch-min-size: 256
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

    listener:
      ack-mode: manual
      type: single

    producer:
      compression-type: lz4
      retries: 5
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

      properties:
        enable:
          idempotence: true


server:
  port: 8082


grpc:
  server:
    port: 9192

  client:
    GLOBAL:
      enable-keep-alive: true
      negotiation-type: plaintext

    ledger-client:
      address: static://127.0.0.1:9191

    account-client:
      address: static://127.0.0.1:9191

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

app:
  kafka:
    not-retriable-exceptions: com.exchange.app.wallet.exception.AbnormalProtoDataException

  outbox:
    interval: "*/5 * * * * ?"
    page-limit: 2

  cache:
    idemp:
      pending-ttl: 120s
      done-ttl: 24h
      jitter-ms: 100
    data:
      entity-cache-ttl: 120s
      index-cache-ttl: 1h
      tombstone-ttl: 120s # should be short to only cover request ttl
      negative-ttl: 30s
      jitter: 100ms
