// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/exchange/proto/ledger/ledger_common.proto

package com.exchange.proto.ledger.common;

/**
 * Protobuf enum {@code ledger.AccountCategoryPb}
 */
public enum AccountCategoryPb
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>AccountCategory_Unknown = 0;</code>
   */
  AccountCategory_Unknown(0),
  /**
   * <code>AccountCategory_Asset = 1;</code>
   */
  AccountCategory_Asset(1),
  /**
   * <code>AccountCategory_Liability = 2;</code>
   */
  AccountCategory_Liability(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>AccountCategory_Unknown = 0;</code>
   */
  public static final int AccountCategory_Unknown_VALUE = 0;
  /**
   * <code>AccountCategory_Asset = 1;</code>
   */
  public static final int AccountCategory_Asset_VALUE = 1;
  /**
   * <code>AccountCategory_Liability = 2;</code>
   */
  public static final int AccountCategory_Liability_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static AccountCategoryPb valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static AccountCategoryPb forNumber(int value) {
    switch (value) {
      case 0: return AccountCategory_Unknown;
      case 1: return AccountCategory_Asset;
      case 2: return AccountCategory_Liability;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AccountCategoryPb>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AccountCategoryPb> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AccountCategoryPb>() {
          public AccountCategoryPb findValueByNumber(int number) {
            return AccountCategoryPb.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.exchange.proto.ledger.common.LedgerCommon.getDescriptor().getEnumTypes().get(1);
  }

  private static final AccountCategoryPb[] VALUES = values();

  public static AccountCategoryPb valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private AccountCategoryPb(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ledger.AccountCategoryPb)
}

