// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/exchange/proto/ledger/ledger_common.proto

package com.exchange.proto.ledger.common;

public final class LedgerCommon {
  private LedgerCommon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-com/exchange/proto/ledger/ledger_commo" +
      "n.proto\022\006ledger*g\n\021LedgerDirectionPb\022\033\n\027" +
      "LedgerDirection_Unknown\020\000\022\032\n\026LedgerDirec" +
      "tion_Credit\020\001\022\031\n\025LedgerDirection_Debit\020\002" +
      "*j\n\021AccountCategoryPb\022\033\n\027AccountCategory" +
      "_Unknown\020\000\022\031\n\025AccountCategory_Asset\020\001\022\035\n" +
      "\031AccountCategory_Liability\020\002*Y\n\014NormalSi" +
      "dePb\022\030\n\024NormalSidePb_Unknown\020\000\022\026\n\022Normal" +
      "SidePb_Debit\020\001\022\027\n\023NormalSidePb_Credit\020\002*" +
      "T\n\013OwnerTypePb\022\027\n\023OwnerTypePb_Unknown\020\000\022" +
      "\026\n\022OwnerTypePb_System\020\001\022\024\n\020OwnerTypePb_U" +
      "ser\020\002*V\n\013ServiceIdPb\022\027\n\023ServiceIdPb_Unkn" +
      "own\020\000\022\026\n\022ServiceIdPb_System\020\001\022\026\n\022Service" +
      "IdPb_Wallet\020\002B$\n com.exchange.proto.ledg" +
      "er.commonP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
