// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ledger/ledger_common.proto

package com.exchange.proto.ledger.common;

/**
 * Protobuf enum {@code ledger.NormalSidePb}
 */
public enum NormalSidePb
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>NormalSidePb_Unknown = 0;</code>
   */
  NormalSidePb_Unknown(0),
  /**
   * <code>NormalSidePb_Debit = 1;</code>
   */
  NormalSidePb_Debit(1),
  /**
   * <code>NormalSidePb_Credit = 2;</code>
   */
  NormalSidePb_Credit(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>NormalSidePb_Unknown = 0;</code>
   */
  public static final int NormalSidePb_Unknown_VALUE = 0;
  /**
   * <code>NormalSidePb_Debit = 1;</code>
   */
  public static final int NormalSidePb_Debit_VALUE = 1;
  /**
   * <code>NormalSidePb_Credit = 2;</code>
   */
  public static final int NormalSidePb_Credit_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static NormalSidePb valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static NormalSidePb forNumber(int value) {
    switch (value) {
      case 0: return NormalSidePb_Unknown;
      case 1: return NormalSidePb_Debit;
      case 2: return NormalSidePb_Credit;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<NormalSidePb>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      NormalSidePb> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<NormalSidePb>() {
          public NormalSidePb findValueByNumber(int number) {
            return NormalSidePb.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.exchange.proto.ledger.common.LedgerCommon.getDescriptor().getEnumTypes().get(2);
  }

  private static final NormalSidePb[] VALUES = values();

  public static NormalSidePb valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private NormalSidePb(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ledger.NormalSidePb)
}

