// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/exchange/proto/ledger/ledger_common.proto

package com.exchange.proto.ledger.common;

/**
 * Protobuf enum {@code ledger.OwnerTypePb}
 */
public enum OwnerTypePb
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>OwnerTypePb_Unknown = 0;</code>
   */
  OwnerTypePb_Unknown(0),
  /**
   * <code>OwnerTypePb_System = 1;</code>
   */
  OwnerTypePb_System(1),
  /**
   * <code>OwnerTypePb_User = 2;</code>
   */
  OwnerTypePb_User(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>OwnerTypePb_Unknown = 0;</code>
   */
  public static final int OwnerTypePb_Unknown_VALUE = 0;
  /**
   * <code>OwnerTypePb_System = 1;</code>
   */
  public static final int OwnerTypePb_System_VALUE = 1;
  /**
   * <code>OwnerTypePb_User = 2;</code>
   */
  public static final int OwnerTypePb_User_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static OwnerTypePb valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static OwnerTypePb forNumber(int value) {
    switch (value) {
      case 0: return OwnerTypePb_Unknown;
      case 1: return OwnerTypePb_System;
      case 2: return OwnerTypePb_User;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<OwnerTypePb>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      OwnerTypePb> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<OwnerTypePb>() {
          public OwnerTypePb findValueByNumber(int number) {
            return OwnerTypePb.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.exchange.proto.ledger.common.LedgerCommon.getDescriptor().getEnumTypes().get(3);
  }

  private static final OwnerTypePb[] VALUES = values();

  public static OwnerTypePb valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private OwnerTypePb(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ledger.OwnerTypePb)
}

