syntax = "proto3";

package wallet;

option java_multiple_files = true;
option java_package = "com.exchange.proto.wallet.wallet";

import "wallet/wallet_enum.proto";
import "com/exchange/proto/common/error.proto";

message AtomicTransactionRequestPb {
  string reference_id = 1;
  ServiceIdPb initiator = 2;
  string idempotency_key = 3;
  BusinessTypePb business_type = 4;
  repeated TransactionLinePb lines = 5;
}

message AtomicTransactionReplyPb {
  common.ErrorPb error = 1;
  string transaction_id = 2;
  TransactionStatusPb status = 3;
}

message TransactionLinePb {
  string wallet_ref = 1;
  string asset_code = 2;
  OperationType operation_type = 3;
  int64 amount = 4;
  string reservation_ref = 5; // used in 2-step transaction, when action_type=consume/release
}
