syntax = "proto3";

package wallet;

option java_multiple_files = true;
option java_package = "com.exchange.proto.wallet.common";

enum OwnerTypePb {
  OwnerTypePb_Unknown = 0;
  OwnerTypePb_System = 1;
  OwnerTypePb_User = 2;
}

enum ServiceIdPb {
  ServiceIdPb_Unknown = 0;
  ServiceIdPb_System = 1;
  ServiceIdPb_User = 2;
}

enum TransactionTypePb {
  TransactionTypePb_Unknown = 0;
  TransactionTypePb_Atomic = 1;
}

enum TransactionStatusPb {
  TransactionStatusPb_Unknown = 0;
  TransactionStatusPb_Pending = 1;
  TransactionStatusPb_Completed = 2;
  TransactionStatusPb_Closed = 3;
}

enum BusinessTypePb {
  BusinessTypePb_Unknown = 0;
  BusinessTypePb_Transfer = 1;
}

enum ActionTypePb {
  ActionTypePb_Unknown = 0;
  ActionTypePb_Reserve = 1;
  ActionTypePb_TransferOut = 2;
  ActionTypePb_TransferIn = 3;
  ActionTypePb_Release = 4;
}

enum OperationTypePb {
  OperationTypePb_Unknown = 0;
  OperationTypePb_Reserve = 1;
  OperationTypePb_Earmark = 2; // confirm and transfer out in 2-step txn
  OperationTypePb_Release = 3;
  OperationTypePb_Debit = 4;   // transfer out in atomic txn
  OperationTypePb_Credit = 5;
}

enum WalletStatusPb {
  WalletStatusPb_Unknown = 0;
  WalletStatusPb_Init = 1;
  WalletStatusPb_Open = 2;
  WalletStatusPb_Frozen = 3;
  WalletStatusPb_Close = 4;
}