// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/exchange/proto/ledger/post_service.proto

package com.exchange.proto.ledger.post;

public interface LedgerEntryPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ledger.LedgerEntryPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string accountRef = 1;</code>
   * @return The accountRef.
   */
  java.lang.String getAccountRef();
  /**
   * <code>string accountRef = 1;</code>
   * @return The bytes for accountRef.
   */
  com.google.protobuf.ByteString
      getAccountRefBytes();

  /**
   * <code>.ledger.LedgerDirectionPb direction = 2;</code>
   * @return The enum numeric value on the wire for direction.
   */
  int getDirectionValue();
  /**
   * <code>.ledger.LedgerDirectionPb direction = 2;</code>
   * @return The direction.
   */
  com.exchange.proto.ledger.common.LedgerDirectionPb getDirection();

  /**
   * <code>int64 amount = 3;</code>
   * @return The amount.
   */
  long getAmount();

  /**
   * <code>string assetId = 4;</code>
   * @return The assetId.
   */
  java.lang.String getAssetId();
  /**
   * <code>string assetId = 4;</code>
   * @return The bytes for assetId.
   */
  com.google.protobuf.ByteString
      getAssetIdBytes();
}
