// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/exchange/proto/ledger/post_service.proto

package com.exchange.proto.ledger.post;

public interface PostTransactionReplyPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ledger.PostTransactionReplyPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.common.ErrorPb error = 1;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.common.ErrorPb error = 1;</code>
   * @return The error.
   */
  com.exchange.proto.common.error.ErrorPb getError();
  /**
   * <code>.common.ErrorPb error = 1;</code>
   */
  com.exchange.proto.common.error.ErrorPbOrBuilder getErrorOrBuilder();
}
