// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/exchange/proto/ledger/post_service.proto

package com.exchange.proto.ledger.post;

public interface PostTransactionRequestPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ledger.PostTransactionRequestPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string referenceId = 1;</code>
   * @return The referenceId.
   */
  java.lang.String getReferenceId();
  /**
   * <code>string referenceId = 1;</code>
   * @return The bytes for referenceId.
   */
  com.google.protobuf.ByteString
      getReferenceIdBytes();

  /**
   * <code>string description = 2;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>repeated .ledger.LedgerEntryPb entries = 3;</code>
   */
  java.util.List<com.exchange.proto.ledger.post.LedgerEntryPb> 
      getEntriesList();
  /**
   * <code>repeated .ledger.LedgerEntryPb entries = 3;</code>
   */
  com.exchange.proto.ledger.post.LedgerEntryPb getEntries(int index);
  /**
   * <code>repeated .ledger.LedgerEntryPb entries = 3;</code>
   */
  int getEntriesCount();
  /**
   * <code>repeated .ledger.LedgerEntryPb entries = 3;</code>
   */
  java.util.List<? extends com.exchange.proto.ledger.post.LedgerEntryPbOrBuilder> 
      getEntriesOrBuilderList();
  /**
   * <code>repeated .ledger.LedgerEntryPb entries = 3;</code>
   */
  com.exchange.proto.ledger.post.LedgerEntryPbOrBuilder getEntriesOrBuilder(
      int index);
}
