// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/exchange/proto/ledger/post_service.proto

package com.exchange.proto.ledger.post;

public final class PostServiceOuterClass {
  private PostServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ledger_PostTransactionRequestPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ledger_PostTransactionRequestPb_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ledger_PostTransactionReplyPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ledger_PostTransactionReplyPb_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ledger_LedgerEntryPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ledger_LedgerEntryPb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,com/exchange/proto/ledger/post_service" +
      ".proto\022\006ledger\032-com/exchange/proto/ledge" +
      "r/ledger_common.proto\032%com/exchange/prot" +
      "o/common/error.proto\"l\n\030PostTransactionR" +
      "equestPb\022\023\n\013referenceId\030\001 \001(\t\022\023\n\013descrip" +
      "tion\030\002 \001(\t\022&\n\007entries\030\003 \003(\0132\025.ledger.Led" +
      "gerEntryPb\"8\n\026PostTransactionReplyPb\022\036\n\005" +
      "error\030\001 \001(\0132\017.common.ErrorPb\"r\n\rLedgerEn" +
      "tryPb\022\022\n\naccountRef\030\001 \001(\t\022,\n\tdirection\030\002" +
      " \001(\0162\031.ledger.LedgerDirectionPb\022\016\n\006amoun" +
      "t\030\003 \001(\003\022\017\n\007assetId\030\004 \001(\t2d\n\013PostService\022" +
      "U\n\017postTransaction\022 .ledger.PostTransact" +
      "ionRequestPb\032\036.ledger.PostTransactionRep" +
      "lyPb\"\000B\"\n\036com.exchange.proto.ledger.post" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.exchange.proto.ledger.common.LedgerCommon.getDescriptor(),
          com.exchange.proto.common.error.Error.getDescriptor(),
        });
    internal_static_ledger_PostTransactionRequestPb_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ledger_PostTransactionRequestPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ledger_PostTransactionRequestPb_descriptor,
        new java.lang.String[] { "ReferenceId", "Description", "Entries", });
    internal_static_ledger_PostTransactionReplyPb_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ledger_PostTransactionReplyPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ledger_PostTransactionReplyPb_descriptor,
        new java.lang.String[] { "Error", });
    internal_static_ledger_LedgerEntryPb_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ledger_LedgerEntryPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ledger_LedgerEntryPb_descriptor,
        new java.lang.String[] { "AccountRef", "Direction", "Amount", "AssetId", });
    com.exchange.proto.ledger.common.LedgerCommon.getDescriptor();
    com.exchange.proto.common.error.Error.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
