syntax = "proto3";

package ledger;

option java_multiple_files = true;
option java_package = "com.exchange.proto.ledger.post";

import "com/exchange/proto/ledger/ledger_common.proto";
import "com/exchange/proto/common/error.proto";

service PostService {
  rpc postTransaction(PostTransactionRequestPb) returns (PostTransactionReplyPb) {}
}

message PostTransactionRequestPb {
  string referenceId = 1;
  string description = 2;
  repeated LedgerEntryPb entries = 3;
}

message PostTransactionReplyPb {
  common.ErrorPb error = 1;
}

message LedgerEntryPb {
  string accountId = 1;
  LedgerDirectionPb direction = 2;
  int64 amount = 3;
  string assetId = 4;
}