// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/exchange/proto/common/error.proto

package com.exchange.proto.common.error;

public final class Error {
  private Error() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_ErrorPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_ErrorPb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%com/exchange/proto/common/error.proto\022" +
      "\006common\"M\n\007ErrorPb\022!\n\004code\030\001 \001(\0162\023.commo" +
      "n.ErrorCodePb\022\017\n\007message\030\002 \001(\t\022\016\n\006detail" +
      "\030\003 \001(\t*\376\001\n\013ErrorCodePb\022\014\n\010ERROR_OK\020\000\022\022\n\016" +
      "ERROR_INTERNAL\020\001\022\025\n\021ERROR_UNAVAILABLE\020\002\022" +
      "\033\n\026ERROR_INVALID_ARGUMENT\020\350\007\022\032\n\025ERROR_UN" +
      "AUTHENTICATED\020\351\007\022\027\n\022ERROR_UNAUTHORIZED\020\352" +
      "\007\022\024\n\017ERROR_NOT_FOUND\020\320\017\022\031\n\024ERROR_ALREADY" +
      "_EXISTS\020\321\017\022\036\n\031ERROR_FAILED_PRECONDITION\020" +
      "\270\027\022\023\n\016ERROR_CONFLICT\020\271\027B#\n\037com.exchange." +
      "proto.common.errorP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_common_ErrorPb_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_common_ErrorPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_ErrorPb_descriptor,
        new java.lang.String[] { "Code", "Message", "Detail", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
