// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/exchange/proto/common/error.proto

package com.exchange.proto.common.error;

public interface ErrorPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.ErrorPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.common.ErrorCodePb code = 1;</code>
   * @return The enum numeric value on the wire for code.
   */
  int getCodeValue();
  /**
   * <code>.common.ErrorCodePb code = 1;</code>
   * @return The code.
   */
  com.exchange.proto.common.error.ErrorCodePb getCode();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string detail = 3;</code>
   * @return The detail.
   */
  java.lang.String getDetail();
  /**
   * <code>string detail = 3;</code>
   * @return The bytes for detail.
   */
  com.google.protobuf.ByteString
      getDetailBytes();
}
