// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/exchange/proto/common/error.proto

package com.exchange.proto.common.error;

/**
 * Protobuf enum {@code common.ErrorCodePb}
 */
public enum ErrorCodePb
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ERROR_OK = 0;</code>
   */
  ERROR_OK(0),
  /**
   * <pre>
   * internal
   * </pre>
   *
   * <code>ERROR_INTERNAL = 1;</code>
   */
  ERROR_INTERNAL(1),
  /**
   * <code>ERROR_UNAVAILABLE = 2;</code>
   */
  ERROR_UNAVAILABLE(2),
  /**
   * <pre>
   * 1xxx validation
   * </pre>
   *
   * <code>ERROR_INVALID_ARGUMENT = 1000;</code>
   */
  ERROR_INVALID_ARGUMENT(1000),
  /**
   * <code>ERROR_UNAUTHENTICATED = 1001;</code>
   */
  ERROR_UNAUTHENTICATED(1001),
  /**
   * <code>ERROR_UNAUTHORIZED = 1002;</code>
   */
  ERROR_UNAUTHORIZED(1002),
  /**
   * <pre>
   * 2xxx resource issues
   * </pre>
   *
   * <code>ERROR_NOT_FOUND = 2000;</code>
   */
  ERROR_NOT_FOUND(2000),
  /**
   * <code>ERROR_ALREADY_EXISTS = 2001;</code>
   */
  ERROR_ALREADY_EXISTS(2001),
  /**
   * <pre>
   * 3xxx business condition violations
   * </pre>
   *
   * <code>ERROR_FAILED_PRECONDITION = 3000;</code>
   */
  ERROR_FAILED_PRECONDITION(3000),
  /**
   * <code>ERROR_CONFLICT = 3001;</code>
   */
  ERROR_CONFLICT(3001),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ERROR_OK = 0;</code>
   */
  public static final int ERROR_OK_VALUE = 0;
  /**
   * <pre>
   * internal
   * </pre>
   *
   * <code>ERROR_INTERNAL = 1;</code>
   */
  public static final int ERROR_INTERNAL_VALUE = 1;
  /**
   * <code>ERROR_UNAVAILABLE = 2;</code>
   */
  public static final int ERROR_UNAVAILABLE_VALUE = 2;
  /**
   * <pre>
   * 1xxx validation
   * </pre>
   *
   * <code>ERROR_INVALID_ARGUMENT = 1000;</code>
   */
  public static final int ERROR_INVALID_ARGUMENT_VALUE = 1000;
  /**
   * <code>ERROR_UNAUTHENTICATED = 1001;</code>
   */
  public static final int ERROR_UNAUTHENTICATED_VALUE = 1001;
  /**
   * <code>ERROR_UNAUTHORIZED = 1002;</code>
   */
  public static final int ERROR_UNAUTHORIZED_VALUE = 1002;
  /**
   * <pre>
   * 2xxx resource issues
   * </pre>
   *
   * <code>ERROR_NOT_FOUND = 2000;</code>
   */
  public static final int ERROR_NOT_FOUND_VALUE = 2000;
  /**
   * <code>ERROR_ALREADY_EXISTS = 2001;</code>
   */
  public static final int ERROR_ALREADY_EXISTS_VALUE = 2001;
  /**
   * <pre>
   * 3xxx business condition violations
   * </pre>
   *
   * <code>ERROR_FAILED_PRECONDITION = 3000;</code>
   */
  public static final int ERROR_FAILED_PRECONDITION_VALUE = 3000;
  /**
   * <code>ERROR_CONFLICT = 3001;</code>
   */
  public static final int ERROR_CONFLICT_VALUE = 3001;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ErrorCodePb valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ErrorCodePb forNumber(int value) {
    switch (value) {
      case 0: return ERROR_OK;
      case 1: return ERROR_INTERNAL;
      case 2: return ERROR_UNAVAILABLE;
      case 1000: return ERROR_INVALID_ARGUMENT;
      case 1001: return ERROR_UNAUTHENTICATED;
      case 1002: return ERROR_UNAUTHORIZED;
      case 2000: return ERROR_NOT_FOUND;
      case 2001: return ERROR_ALREADY_EXISTS;
      case 3000: return ERROR_FAILED_PRECONDITION;
      case 3001: return ERROR_CONFLICT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ErrorCodePb>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ErrorCodePb> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ErrorCodePb>() {
          public ErrorCodePb findValueByNumber(int number) {
            return ErrorCodePb.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.exchange.proto.common.error.Error.getDescriptor().getEnumTypes().get(0);
  }

  private static final ErrorCodePb[] VALUES = values();

  public static ErrorCodePb valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ErrorCodePb(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:common.ErrorCodePb)
}

