// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ledger/account_service.proto

package com.example.proto.ledger.account;

public final class AccountServiceOuterClass {
  private AccountServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ledger_CreateAccountRequestPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ledger_CreateAccountRequestPb_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ledger_CreateAccountReplyPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ledger_CreateAccountReplyPb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034ledger/account_service.proto\022\006ledger\032\032" +
      "ledger/ledger_common.proto\"\374\001\n\026CreateAcc" +
      "ountRequestPb\022\024\n\014reference_id\030\001 \001(\t\022\'\n\ns" +
      "ervice_id\030\002 \001(\0162\023.ledger.ServiceIdPb\022\020\n\010" +
      "asset_id\030\003 \001(\t\022+\n\010category\030\004 \001(\0162\031.ledge" +
      "r.AccountCategoryPb\022)\n\013normal_side\030\005 \001(\016" +
      "2\024.ledger.NormalSidePb\022\'\n\nowner_type\030\006 \001" +
      "(\0162\023.ledger.OwnerTypePb\022\020\n\010owner_id\030\007 \001(" +
      "\t\"1\n\024CreateAccountReplyPb\022\014\n\004code\030\001 \001(\005\022" +
      "\013\n\003msg\030\002 \001(\t2a\n\016AccountService\022O\n\rcreate" +
      "Account\022\036.ledger.CreateAccountRequestPb\032" +
      "\034.ledger.CreateAccountReplyPb\"\000B$\n com.e" +
      "xample.proto.ledger.accountP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.example.proto.ledger.common.LedgerCommon.getDescriptor(),
        });
    internal_static_ledger_CreateAccountRequestPb_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ledger_CreateAccountRequestPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ledger_CreateAccountRequestPb_descriptor,
        new java.lang.String[] { "ReferenceId", "ServiceId", "AssetId", "Category", "NormalSide", "OwnerType", "OwnerId", });
    internal_static_ledger_CreateAccountReplyPb_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ledger_CreateAccountReplyPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ledger_CreateAccountReplyPb_descriptor,
        new java.lang.String[] { "Code", "Msg", });
    com.example.proto.ledger.common.LedgerCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
