// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ledger/account_service.proto

package com.example.proto.ledger.account;

public interface CreateAccountRequestPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ledger.CreateAccountRequestPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reference_id = 1;</code>
   * @return The referenceId.
   */
  java.lang.String getReferenceId();
  /**
   * <code>string reference_id = 1;</code>
   * @return The bytes for referenceId.
   */
  com.google.protobuf.ByteString
      getReferenceIdBytes();

  /**
   * <code>.ledger.ServiceIdPb service_id = 2;</code>
   * @return The enum numeric value on the wire for serviceId.
   */
  int getServiceIdValue();
  /**
   * <code>.ledger.ServiceIdPb service_id = 2;</code>
   * @return The serviceId.
   */
  com.example.proto.ledger.common.ServiceIdPb getServiceId();

  /**
   * <code>string asset_id = 3;</code>
   * @return The assetId.
   */
  java.lang.String getAssetId();
  /**
   * <code>string asset_id = 3;</code>
   * @return The bytes for assetId.
   */
  com.google.protobuf.ByteString
      getAssetIdBytes();

  /**
   * <code>.ledger.AccountCategoryPb category = 4;</code>
   * @return The enum numeric value on the wire for category.
   */
  int getCategoryValue();
  /**
   * <code>.ledger.AccountCategoryPb category = 4;</code>
   * @return The category.
   */
  com.example.proto.ledger.common.AccountCategoryPb getCategory();

  /**
   * <code>.ledger.NormalSidePb normal_side = 5;</code>
   * @return The enum numeric value on the wire for normalSide.
   */
  int getNormalSideValue();
  /**
   * <code>.ledger.NormalSidePb normal_side = 5;</code>
   * @return The normalSide.
   */
  com.example.proto.ledger.common.NormalSidePb getNormalSide();

  /**
   * <code>.ledger.OwnerTypePb owner_type = 6;</code>
   * @return The enum numeric value on the wire for ownerType.
   */
  int getOwnerTypeValue();
  /**
   * <code>.ledger.OwnerTypePb owner_type = 6;</code>
   * @return The ownerType.
   */
  com.example.proto.ledger.common.OwnerTypePb getOwnerType();

  /**
   * <code>string owner_id = 7;</code>
   * @return The ownerId.
   */
  java.lang.String getOwnerId();
  /**
   * <code>string owner_id = 7;</code>
   * @return The bytes for ownerId.
   */
  com.google.protobuf.ByteString
      getOwnerIdBytes();
}
