// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ledger/account_service.proto

package com.example.proto.ledger.account;

public interface CreateAccountReplyPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ledger.CreateAccountReplyPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string msg = 2;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 2;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
