// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ledger/ledger_common.proto

package com.example.proto.ledger.common;

/**
 * Protobuf enum {@code ledger.LedgerDirectionPb}
 */
public enum LedgerDirectionPb
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>LedgerDirection_Unknown = 0;</code>
   */
  LedgerDirection_Unknown(0),
  /**
   * <code>LedgerDirection_Credit = 1;</code>
   */
  LedgerDirection_Credit(1),
  /**
   * <code>LedgerDirection_Debit = 2;</code>
   */
  LedgerDirection_Debit(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>LedgerDirection_Unknown = 0;</code>
   */
  public static final int LedgerDirection_Unknown_VALUE = 0;
  /**
   * <code>LedgerDirection_Credit = 1;</code>
   */
  public static final int LedgerDirection_Credit_VALUE = 1;
  /**
   * <code>LedgerDirection_Debit = 2;</code>
   */
  public static final int LedgerDirection_Debit_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static LedgerDirectionPb valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static LedgerDirectionPb forNumber(int value) {
    switch (value) {
      case 0: return LedgerDirection_Unknown;
      case 1: return LedgerDirection_Credit;
      case 2: return LedgerDirection_Debit;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<LedgerDirectionPb>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      LedgerDirectionPb> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<LedgerDirectionPb>() {
          public LedgerDirectionPb findValueByNumber(int number) {
            return LedgerDirectionPb.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.example.proto.ledger.common.LedgerCommon.getDescriptor().getEnumTypes().get(0);
  }

  private static final LedgerDirectionPb[] VALUES = values();

  public static LedgerDirectionPb valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private LedgerDirectionPb(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ledger.LedgerDirectionPb)
}

