// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ledger/ledger_common.proto

package com.example.proto.ledger.common;

public final class LedgerCommon {
  private LedgerCommon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032ledger/ledger_common.proto\022\006ledger*g\n\021" +
      "LedgerDirectionPb\022\033\n\027LedgerDirection_Unk" +
      "nown\020\000\022\032\n\026LedgerDirection_Credit\020\001\022\031\n\025Le" +
      "dgerDirection_Debit\020\002*j\n\021AccountCategory" +
      "Pb\022\033\n\027AccountCategory_Unknown\020\000\022\031\n\025Accou" +
      "ntCategory_Asset\020\001\022\035\n\031AccountCategory_Li" +
      "ability\020\002*Y\n\014NormalSidePb\022\030\n\024NormalSideP" +
      "b_Unknown\020\000\022\026\n\022NormalSidePb_Debit\020\001\022\027\n\023N" +
      "ormalSidePb_Credit\020\002*T\n\013OwnerTypePb\022\027\n\023O" +
      "wnerTypePb_Unknown\020\000\022\026\n\022OwnerTypePb_Syst" +
      "em\020\001\022\024\n\020OwnerTypePb_User\020\002*V\n\013ServiceIdP" +
      "b\022\027\n\023ServiceIdPb_Unknown\020\000\022\026\n\022ServiceIdP" +
      "b_System\020\001\022\026\n\022ServiceIdPb_Wallet\020\002B#\n\037co" +
      "m.example.proto.ledger.commonP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
