// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet/create_wallet.proto

package com.example.proto.wallet;

public interface CreateWalletRequestPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wallet.CreateWalletRequestPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.wallet.ServiceIdPb service_id = 1;</code>
   * @return The enum numeric value on the wire for serviceId.
   */
  int getServiceIdValue();
  /**
   * <code>.wallet.ServiceIdPb service_id = 1;</code>
   * @return The serviceId.
   */
  com.example.proto.wallet.common.ServiceIdPb getServiceId();

  /**
   * <code>string reference_id = 2;</code>
   * @return The referenceId.
   */
  java.lang.String getReferenceId();
  /**
   * <code>string reference_id = 2;</code>
   * @return The bytes for referenceId.
   */
  com.google.protobuf.ByteString
      getReferenceIdBytes();

  /**
   * <code>string asset_id = 3;</code>
   * @return The assetId.
   */
  java.lang.String getAssetId();
  /**
   * <code>string asset_id = 3;</code>
   * @return The bytes for assetId.
   */
  com.google.protobuf.ByteString
      getAssetIdBytes();

  /**
   * <code>.wallet.OwnerTypePb owner_type = 4;</code>
   * @return The enum numeric value on the wire for ownerType.
   */
  int getOwnerTypeValue();
  /**
   * <code>.wallet.OwnerTypePb owner_type = 4;</code>
   * @return The ownerType.
   */
  com.example.proto.wallet.common.OwnerTypePb getOwnerType();

  /**
   * <code>string owner_id = 5;</code>
   * @return The ownerId.
   */
  java.lang.String getOwnerId();
  /**
   * <code>string owner_id = 5;</code>
   * @return The bytes for ownerId.
   */
  com.google.protobuf.ByteString
      getOwnerIdBytes();
}
