// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/exchange/proto/ledger/account_service.proto

package com.exchange.proto.ledger.account;

/**
 * Protobuf type {@code ledger.CreateAccountReplyPb}
 */
public final class CreateAccountReplyPb extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ledger.CreateAccountReplyPb)
    CreateAccountReplyPbOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateAccountReplyPb.newBuilder() to construct.
  private CreateAccountReplyPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateAccountReplyPb() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateAccountReplyPb();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateAccountReplyPb(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.exchange.proto.common.error.ErrorPb.Builder subBuilder = null;
            if (error_ != null) {
              subBuilder = error_.toBuilder();
            }
            error_ = input.readMessage(com.exchange.proto.common.error.ErrorPb.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(error_);
              error_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.exchange.proto.ledger.account.AccountServiceOuterClass.internal_static_ledger_CreateAccountReplyPb_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.exchange.proto.ledger.account.AccountServiceOuterClass.internal_static_ledger_CreateAccountReplyPb_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.exchange.proto.ledger.account.CreateAccountReplyPb.class, com.exchange.proto.ledger.account.CreateAccountReplyPb.Builder.class);
  }

  public static final int ERROR_FIELD_NUMBER = 1;
  private com.exchange.proto.common.error.ErrorPb error_;
  /**
   * <code>.common.ErrorPb error = 1;</code>
   * @return Whether the error field is set.
   */
  @java.lang.Override
  public boolean hasError() {
    return error_ != null;
  }
  /**
   * <code>.common.ErrorPb error = 1;</code>
   * @return The error.
   */
  @java.lang.Override
  public com.exchange.proto.common.error.ErrorPb getError() {
    return error_ == null ? com.exchange.proto.common.error.ErrorPb.getDefaultInstance() : error_;
  }
  /**
   * <code>.common.ErrorPb error = 1;</code>
   */
  @java.lang.Override
  public com.exchange.proto.common.error.ErrorPbOrBuilder getErrorOrBuilder() {
    return getError();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (error_ != null) {
      output.writeMessage(1, getError());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (error_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getError());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.exchange.proto.ledger.account.CreateAccountReplyPb)) {
      return super.equals(obj);
    }
    com.exchange.proto.ledger.account.CreateAccountReplyPb other = (com.exchange.proto.ledger.account.CreateAccountReplyPb) obj;

    if (hasError() != other.hasError()) return false;
    if (hasError()) {
      if (!getError()
          .equals(other.getError())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.exchange.proto.ledger.account.CreateAccountReplyPb parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.exchange.proto.ledger.account.CreateAccountReplyPb parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.exchange.proto.ledger.account.CreateAccountReplyPb parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.exchange.proto.ledger.account.CreateAccountReplyPb parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.exchange.proto.ledger.account.CreateAccountReplyPb parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.exchange.proto.ledger.account.CreateAccountReplyPb parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.exchange.proto.ledger.account.CreateAccountReplyPb parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.exchange.proto.ledger.account.CreateAccountReplyPb parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.exchange.proto.ledger.account.CreateAccountReplyPb parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.exchange.proto.ledger.account.CreateAccountReplyPb parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.exchange.proto.ledger.account.CreateAccountReplyPb parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.exchange.proto.ledger.account.CreateAccountReplyPb parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.exchange.proto.ledger.account.CreateAccountReplyPb prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ledger.CreateAccountReplyPb}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ledger.CreateAccountReplyPb)
      com.exchange.proto.ledger.account.CreateAccountReplyPbOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.exchange.proto.ledger.account.AccountServiceOuterClass.internal_static_ledger_CreateAccountReplyPb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.exchange.proto.ledger.account.AccountServiceOuterClass.internal_static_ledger_CreateAccountReplyPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.exchange.proto.ledger.account.CreateAccountReplyPb.class, com.exchange.proto.ledger.account.CreateAccountReplyPb.Builder.class);
    }

    // Construct using com.exchange.proto.ledger.account.CreateAccountReplyPb.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (errorBuilder_ == null) {
        error_ = null;
      } else {
        error_ = null;
        errorBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.exchange.proto.ledger.account.AccountServiceOuterClass.internal_static_ledger_CreateAccountReplyPb_descriptor;
    }

    @java.lang.Override
    public com.exchange.proto.ledger.account.CreateAccountReplyPb getDefaultInstanceForType() {
      return com.exchange.proto.ledger.account.CreateAccountReplyPb.getDefaultInstance();
    }

    @java.lang.Override
    public com.exchange.proto.ledger.account.CreateAccountReplyPb build() {
      com.exchange.proto.ledger.account.CreateAccountReplyPb result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.exchange.proto.ledger.account.CreateAccountReplyPb buildPartial() {
      com.exchange.proto.ledger.account.CreateAccountReplyPb result = new com.exchange.proto.ledger.account.CreateAccountReplyPb(this);
      if (errorBuilder_ == null) {
        result.error_ = error_;
      } else {
        result.error_ = errorBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.exchange.proto.ledger.account.CreateAccountReplyPb) {
        return mergeFrom((com.exchange.proto.ledger.account.CreateAccountReplyPb)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.exchange.proto.ledger.account.CreateAccountReplyPb other) {
      if (other == com.exchange.proto.ledger.account.CreateAccountReplyPb.getDefaultInstance()) return this;
      if (other.hasError()) {
        mergeError(other.getError());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.exchange.proto.ledger.account.CreateAccountReplyPb parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.exchange.proto.ledger.account.CreateAccountReplyPb) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.exchange.proto.common.error.ErrorPb error_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.exchange.proto.common.error.ErrorPb, com.exchange.proto.common.error.ErrorPb.Builder, com.exchange.proto.common.error.ErrorPbOrBuilder> errorBuilder_;
    /**
     * <code>.common.ErrorPb error = 1;</code>
     * @return Whether the error field is set.
     */
    public boolean hasError() {
      return errorBuilder_ != null || error_ != null;
    }
    /**
     * <code>.common.ErrorPb error = 1;</code>
     * @return The error.
     */
    public com.exchange.proto.common.error.ErrorPb getError() {
      if (errorBuilder_ == null) {
        return error_ == null ? com.exchange.proto.common.error.ErrorPb.getDefaultInstance() : error_;
      } else {
        return errorBuilder_.getMessage();
      }
    }
    /**
     * <code>.common.ErrorPb error = 1;</code>
     */
    public Builder setError(com.exchange.proto.common.error.ErrorPb value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        error_ = value;
        onChanged();
      } else {
        errorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.common.ErrorPb error = 1;</code>
     */
    public Builder setError(
        com.exchange.proto.common.error.ErrorPb.Builder builderForValue) {
      if (errorBuilder_ == null) {
        error_ = builderForValue.build();
        onChanged();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.common.ErrorPb error = 1;</code>
     */
    public Builder mergeError(com.exchange.proto.common.error.ErrorPb value) {
      if (errorBuilder_ == null) {
        if (error_ != null) {
          error_ =
            com.exchange.proto.common.error.ErrorPb.newBuilder(error_).mergeFrom(value).buildPartial();
        } else {
          error_ = value;
        }
        onChanged();
      } else {
        errorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.common.ErrorPb error = 1;</code>
     */
    public Builder clearError() {
      if (errorBuilder_ == null) {
        error_ = null;
        onChanged();
      } else {
        error_ = null;
        errorBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.common.ErrorPb error = 1;</code>
     */
    public com.exchange.proto.common.error.ErrorPb.Builder getErrorBuilder() {
      
      onChanged();
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <code>.common.ErrorPb error = 1;</code>
     */
    public com.exchange.proto.common.error.ErrorPbOrBuilder getErrorOrBuilder() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        return error_ == null ?
            com.exchange.proto.common.error.ErrorPb.getDefaultInstance() : error_;
      }
    }
    /**
     * <code>.common.ErrorPb error = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.exchange.proto.common.error.ErrorPb, com.exchange.proto.common.error.ErrorPb.Builder, com.exchange.proto.common.error.ErrorPbOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.exchange.proto.common.error.ErrorPb, com.exchange.proto.common.error.ErrorPb.Builder, com.exchange.proto.common.error.ErrorPbOrBuilder>(
                getError(),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ledger.CreateAccountReplyPb)
  }

  // @@protoc_insertion_point(class_scope:ledger.CreateAccountReplyPb)
  private static final com.exchange.proto.ledger.account.CreateAccountReplyPb DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.exchange.proto.ledger.account.CreateAccountReplyPb();
  }

  public static com.exchange.proto.ledger.account.CreateAccountReplyPb getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateAccountReplyPb>
      PARSER = new com.google.protobuf.AbstractParser<CreateAccountReplyPb>() {
    @java.lang.Override
    public CreateAccountReplyPb parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateAccountReplyPb(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateAccountReplyPb> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateAccountReplyPb> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.exchange.proto.ledger.account.CreateAccountReplyPb getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

