// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/exchange/proto/ledger/account_service.proto

package com.exchange.proto.ledger.account;

/**
 * Protobuf type {@code ledger.CreateAccountRequestPb}
 */
public final class CreateAccountRequestPb extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ledger.CreateAccountRequestPb)
    CreateAccountRequestPbOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateAccountRequestPb.newBuilder() to construct.
  private CreateAccountRequestPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateAccountRequestPb() {
    referenceId_ = "";
    serviceId_ = 0;
    assetId_ = "";
    category_ = 0;
    normalSide_ = 0;
    ownerType_ = 0;
    ownerId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateAccountRequestPb();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateAccountRequestPb(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            referenceId_ = s;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            serviceId_ = rawValue;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            assetId_ = s;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            category_ = rawValue;
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            normalSide_ = rawValue;
            break;
          }
          case 48: {
            int rawValue = input.readEnum();

            ownerType_ = rawValue;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            ownerId_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.exchange.proto.ledger.account.AccountServiceOuterClass.internal_static_ledger_CreateAccountRequestPb_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.exchange.proto.ledger.account.AccountServiceOuterClass.internal_static_ledger_CreateAccountRequestPb_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.exchange.proto.ledger.account.CreateAccountRequestPb.class, com.exchange.proto.ledger.account.CreateAccountRequestPb.Builder.class);
  }

  public static final int REFERENCE_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object referenceId_;
  /**
   * <code>string reference_id = 1;</code>
   * @return The referenceId.
   */
  @java.lang.Override
  public java.lang.String getReferenceId() {
    java.lang.Object ref = referenceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      referenceId_ = s;
      return s;
    }
  }
  /**
   * <code>string reference_id = 1;</code>
   * @return The bytes for referenceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReferenceIdBytes() {
    java.lang.Object ref = referenceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      referenceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVICE_ID_FIELD_NUMBER = 2;
  private int serviceId_;
  /**
   * <code>.ledger.ServiceIdPb service_id = 2;</code>
   * @return The enum numeric value on the wire for serviceId.
   */
  @java.lang.Override public int getServiceIdValue() {
    return serviceId_;
  }
  /**
   * <code>.ledger.ServiceIdPb service_id = 2;</code>
   * @return The serviceId.
   */
  @java.lang.Override public com.exchange.proto.ledger.common.ServiceIdPb getServiceId() {
    @SuppressWarnings("deprecation")
    com.exchange.proto.ledger.common.ServiceIdPb result = com.exchange.proto.ledger.common.ServiceIdPb.valueOf(serviceId_);
    return result == null ? com.exchange.proto.ledger.common.ServiceIdPb.UNRECOGNIZED : result;
  }

  public static final int ASSET_ID_FIELD_NUMBER = 3;
  private volatile java.lang.Object assetId_;
  /**
   * <code>string asset_id = 3;</code>
   * @return The assetId.
   */
  @java.lang.Override
  public java.lang.String getAssetId() {
    java.lang.Object ref = assetId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      assetId_ = s;
      return s;
    }
  }
  /**
   * <code>string asset_id = 3;</code>
   * @return The bytes for assetId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAssetIdBytes() {
    java.lang.Object ref = assetId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      assetId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CATEGORY_FIELD_NUMBER = 4;
  private int category_;
  /**
   * <code>.ledger.AccountCategoryPb category = 4;</code>
   * @return The enum numeric value on the wire for category.
   */
  @java.lang.Override public int getCategoryValue() {
    return category_;
  }
  /**
   * <code>.ledger.AccountCategoryPb category = 4;</code>
   * @return The category.
   */
  @java.lang.Override public com.exchange.proto.ledger.common.AccountCategoryPb getCategory() {
    @SuppressWarnings("deprecation")
    com.exchange.proto.ledger.common.AccountCategoryPb result = com.exchange.proto.ledger.common.AccountCategoryPb.valueOf(category_);
    return result == null ? com.exchange.proto.ledger.common.AccountCategoryPb.UNRECOGNIZED : result;
  }

  public static final int NORMAL_SIDE_FIELD_NUMBER = 5;
  private int normalSide_;
  /**
   * <code>.ledger.NormalSidePb normal_side = 5;</code>
   * @return The enum numeric value on the wire for normalSide.
   */
  @java.lang.Override public int getNormalSideValue() {
    return normalSide_;
  }
  /**
   * <code>.ledger.NormalSidePb normal_side = 5;</code>
   * @return The normalSide.
   */
  @java.lang.Override public com.exchange.proto.ledger.common.NormalSidePb getNormalSide() {
    @SuppressWarnings("deprecation")
    com.exchange.proto.ledger.common.NormalSidePb result = com.exchange.proto.ledger.common.NormalSidePb.valueOf(normalSide_);
    return result == null ? com.exchange.proto.ledger.common.NormalSidePb.UNRECOGNIZED : result;
  }

  public static final int OWNER_TYPE_FIELD_NUMBER = 6;
  private int ownerType_;
  /**
   * <code>.ledger.OwnerTypePb owner_type = 6;</code>
   * @return The enum numeric value on the wire for ownerType.
   */
  @java.lang.Override public int getOwnerTypeValue() {
    return ownerType_;
  }
  /**
   * <code>.ledger.OwnerTypePb owner_type = 6;</code>
   * @return The ownerType.
   */
  @java.lang.Override public com.exchange.proto.ledger.common.OwnerTypePb getOwnerType() {
    @SuppressWarnings("deprecation")
    com.exchange.proto.ledger.common.OwnerTypePb result = com.exchange.proto.ledger.common.OwnerTypePb.valueOf(ownerType_);
    return result == null ? com.exchange.proto.ledger.common.OwnerTypePb.UNRECOGNIZED : result;
  }

  public static final int OWNER_ID_FIELD_NUMBER = 7;
  private volatile java.lang.Object ownerId_;
  /**
   * <code>string owner_id = 7;</code>
   * @return The ownerId.
   */
  @java.lang.Override
  public java.lang.String getOwnerId() {
    java.lang.Object ref = ownerId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ownerId_ = s;
      return s;
    }
  }
  /**
   * <code>string owner_id = 7;</code>
   * @return The bytes for ownerId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOwnerIdBytes() {
    java.lang.Object ref = ownerId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ownerId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getReferenceIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, referenceId_);
    }
    if (serviceId_ != com.exchange.proto.ledger.common.ServiceIdPb.ServiceIdPb_Unknown.getNumber()) {
      output.writeEnum(2, serviceId_);
    }
    if (!getAssetIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, assetId_);
    }
    if (category_ != com.exchange.proto.ledger.common.AccountCategoryPb.AccountCategory_Unknown.getNumber()) {
      output.writeEnum(4, category_);
    }
    if (normalSide_ != com.exchange.proto.ledger.common.NormalSidePb.NormalSidePb_Unknown.getNumber()) {
      output.writeEnum(5, normalSide_);
    }
    if (ownerType_ != com.exchange.proto.ledger.common.OwnerTypePb.OwnerTypePb_Unknown.getNumber()) {
      output.writeEnum(6, ownerType_);
    }
    if (!getOwnerIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, ownerId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getReferenceIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, referenceId_);
    }
    if (serviceId_ != com.exchange.proto.ledger.common.ServiceIdPb.ServiceIdPb_Unknown.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, serviceId_);
    }
    if (!getAssetIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, assetId_);
    }
    if (category_ != com.exchange.proto.ledger.common.AccountCategoryPb.AccountCategory_Unknown.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, category_);
    }
    if (normalSide_ != com.exchange.proto.ledger.common.NormalSidePb.NormalSidePb_Unknown.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, normalSide_);
    }
    if (ownerType_ != com.exchange.proto.ledger.common.OwnerTypePb.OwnerTypePb_Unknown.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, ownerType_);
    }
    if (!getOwnerIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, ownerId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.exchange.proto.ledger.account.CreateAccountRequestPb)) {
      return super.equals(obj);
    }
    com.exchange.proto.ledger.account.CreateAccountRequestPb other = (com.exchange.proto.ledger.account.CreateAccountRequestPb) obj;

    if (!getReferenceId()
        .equals(other.getReferenceId())) return false;
    if (serviceId_ != other.serviceId_) return false;
    if (!getAssetId()
        .equals(other.getAssetId())) return false;
    if (category_ != other.category_) return false;
    if (normalSide_ != other.normalSide_) return false;
    if (ownerType_ != other.ownerType_) return false;
    if (!getOwnerId()
        .equals(other.getOwnerId())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REFERENCE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getReferenceId().hashCode();
    hash = (37 * hash) + SERVICE_ID_FIELD_NUMBER;
    hash = (53 * hash) + serviceId_;
    hash = (37 * hash) + ASSET_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAssetId().hashCode();
    hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
    hash = (53 * hash) + category_;
    hash = (37 * hash) + NORMAL_SIDE_FIELD_NUMBER;
    hash = (53 * hash) + normalSide_;
    hash = (37 * hash) + OWNER_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + ownerType_;
    hash = (37 * hash) + OWNER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getOwnerId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.exchange.proto.ledger.account.CreateAccountRequestPb parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.exchange.proto.ledger.account.CreateAccountRequestPb parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.exchange.proto.ledger.account.CreateAccountRequestPb parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.exchange.proto.ledger.account.CreateAccountRequestPb parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.exchange.proto.ledger.account.CreateAccountRequestPb parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.exchange.proto.ledger.account.CreateAccountRequestPb parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.exchange.proto.ledger.account.CreateAccountRequestPb parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.exchange.proto.ledger.account.CreateAccountRequestPb parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.exchange.proto.ledger.account.CreateAccountRequestPb parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.exchange.proto.ledger.account.CreateAccountRequestPb parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.exchange.proto.ledger.account.CreateAccountRequestPb parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.exchange.proto.ledger.account.CreateAccountRequestPb parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.exchange.proto.ledger.account.CreateAccountRequestPb prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ledger.CreateAccountRequestPb}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ledger.CreateAccountRequestPb)
      com.exchange.proto.ledger.account.CreateAccountRequestPbOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.exchange.proto.ledger.account.AccountServiceOuterClass.internal_static_ledger_CreateAccountRequestPb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.exchange.proto.ledger.account.AccountServiceOuterClass.internal_static_ledger_CreateAccountRequestPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.exchange.proto.ledger.account.CreateAccountRequestPb.class, com.exchange.proto.ledger.account.CreateAccountRequestPb.Builder.class);
    }

    // Construct using com.exchange.proto.ledger.account.CreateAccountRequestPb.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      referenceId_ = "";

      serviceId_ = 0;

      assetId_ = "";

      category_ = 0;

      normalSide_ = 0;

      ownerType_ = 0;

      ownerId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.exchange.proto.ledger.account.AccountServiceOuterClass.internal_static_ledger_CreateAccountRequestPb_descriptor;
    }

    @java.lang.Override
    public com.exchange.proto.ledger.account.CreateAccountRequestPb getDefaultInstanceForType() {
      return com.exchange.proto.ledger.account.CreateAccountRequestPb.getDefaultInstance();
    }

    @java.lang.Override
    public com.exchange.proto.ledger.account.CreateAccountRequestPb build() {
      com.exchange.proto.ledger.account.CreateAccountRequestPb result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.exchange.proto.ledger.account.CreateAccountRequestPb buildPartial() {
      com.exchange.proto.ledger.account.CreateAccountRequestPb result = new com.exchange.proto.ledger.account.CreateAccountRequestPb(this);
      result.referenceId_ = referenceId_;
      result.serviceId_ = serviceId_;
      result.assetId_ = assetId_;
      result.category_ = category_;
      result.normalSide_ = normalSide_;
      result.ownerType_ = ownerType_;
      result.ownerId_ = ownerId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.exchange.proto.ledger.account.CreateAccountRequestPb) {
        return mergeFrom((com.exchange.proto.ledger.account.CreateAccountRequestPb)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.exchange.proto.ledger.account.CreateAccountRequestPb other) {
      if (other == com.exchange.proto.ledger.account.CreateAccountRequestPb.getDefaultInstance()) return this;
      if (!other.getReferenceId().isEmpty()) {
        referenceId_ = other.referenceId_;
        onChanged();
      }
      if (other.serviceId_ != 0) {
        setServiceIdValue(other.getServiceIdValue());
      }
      if (!other.getAssetId().isEmpty()) {
        assetId_ = other.assetId_;
        onChanged();
      }
      if (other.category_ != 0) {
        setCategoryValue(other.getCategoryValue());
      }
      if (other.normalSide_ != 0) {
        setNormalSideValue(other.getNormalSideValue());
      }
      if (other.ownerType_ != 0) {
        setOwnerTypeValue(other.getOwnerTypeValue());
      }
      if (!other.getOwnerId().isEmpty()) {
        ownerId_ = other.ownerId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.exchange.proto.ledger.account.CreateAccountRequestPb parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.exchange.proto.ledger.account.CreateAccountRequestPb) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object referenceId_ = "";
    /**
     * <code>string reference_id = 1;</code>
     * @return The referenceId.
     */
    public java.lang.String getReferenceId() {
      java.lang.Object ref = referenceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        referenceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string reference_id = 1;</code>
     * @return The bytes for referenceId.
     */
    public com.google.protobuf.ByteString
        getReferenceIdBytes() {
      java.lang.Object ref = referenceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        referenceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string reference_id = 1;</code>
     * @param value The referenceId to set.
     * @return This builder for chaining.
     */
    public Builder setReferenceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      referenceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string reference_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReferenceId() {
      
      referenceId_ = getDefaultInstance().getReferenceId();
      onChanged();
      return this;
    }
    /**
     * <code>string reference_id = 1;</code>
     * @param value The bytes for referenceId to set.
     * @return This builder for chaining.
     */
    public Builder setReferenceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      referenceId_ = value;
      onChanged();
      return this;
    }

    private int serviceId_ = 0;
    /**
     * <code>.ledger.ServiceIdPb service_id = 2;</code>
     * @return The enum numeric value on the wire for serviceId.
     */
    @java.lang.Override public int getServiceIdValue() {
      return serviceId_;
    }
    /**
     * <code>.ledger.ServiceIdPb service_id = 2;</code>
     * @param value The enum numeric value on the wire for serviceId to set.
     * @return This builder for chaining.
     */
    public Builder setServiceIdValue(int value) {
      
      serviceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.ledger.ServiceIdPb service_id = 2;</code>
     * @return The serviceId.
     */
    @java.lang.Override
    public com.exchange.proto.ledger.common.ServiceIdPb getServiceId() {
      @SuppressWarnings("deprecation")
      com.exchange.proto.ledger.common.ServiceIdPb result = com.exchange.proto.ledger.common.ServiceIdPb.valueOf(serviceId_);
      return result == null ? com.exchange.proto.ledger.common.ServiceIdPb.UNRECOGNIZED : result;
    }
    /**
     * <code>.ledger.ServiceIdPb service_id = 2;</code>
     * @param value The serviceId to set.
     * @return This builder for chaining.
     */
    public Builder setServiceId(com.exchange.proto.ledger.common.ServiceIdPb value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      serviceId_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ledger.ServiceIdPb service_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearServiceId() {
      
      serviceId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object assetId_ = "";
    /**
     * <code>string asset_id = 3;</code>
     * @return The assetId.
     */
    public java.lang.String getAssetId() {
      java.lang.Object ref = assetId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        assetId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string asset_id = 3;</code>
     * @return The bytes for assetId.
     */
    public com.google.protobuf.ByteString
        getAssetIdBytes() {
      java.lang.Object ref = assetId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        assetId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string asset_id = 3;</code>
     * @param value The assetId to set.
     * @return This builder for chaining.
     */
    public Builder setAssetId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      assetId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string asset_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAssetId() {
      
      assetId_ = getDefaultInstance().getAssetId();
      onChanged();
      return this;
    }
    /**
     * <code>string asset_id = 3;</code>
     * @param value The bytes for assetId to set.
     * @return This builder for chaining.
     */
    public Builder setAssetIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      assetId_ = value;
      onChanged();
      return this;
    }

    private int category_ = 0;
    /**
     * <code>.ledger.AccountCategoryPb category = 4;</code>
     * @return The enum numeric value on the wire for category.
     */
    @java.lang.Override public int getCategoryValue() {
      return category_;
    }
    /**
     * <code>.ledger.AccountCategoryPb category = 4;</code>
     * @param value The enum numeric value on the wire for category to set.
     * @return This builder for chaining.
     */
    public Builder setCategoryValue(int value) {
      
      category_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.ledger.AccountCategoryPb category = 4;</code>
     * @return The category.
     */
    @java.lang.Override
    public com.exchange.proto.ledger.common.AccountCategoryPb getCategory() {
      @SuppressWarnings("deprecation")
      com.exchange.proto.ledger.common.AccountCategoryPb result = com.exchange.proto.ledger.common.AccountCategoryPb.valueOf(category_);
      return result == null ? com.exchange.proto.ledger.common.AccountCategoryPb.UNRECOGNIZED : result;
    }
    /**
     * <code>.ledger.AccountCategoryPb category = 4;</code>
     * @param value The category to set.
     * @return This builder for chaining.
     */
    public Builder setCategory(com.exchange.proto.ledger.common.AccountCategoryPb value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      category_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ledger.AccountCategoryPb category = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCategory() {
      
      category_ = 0;
      onChanged();
      return this;
    }

    private int normalSide_ = 0;
    /**
     * <code>.ledger.NormalSidePb normal_side = 5;</code>
     * @return The enum numeric value on the wire for normalSide.
     */
    @java.lang.Override public int getNormalSideValue() {
      return normalSide_;
    }
    /**
     * <code>.ledger.NormalSidePb normal_side = 5;</code>
     * @param value The enum numeric value on the wire for normalSide to set.
     * @return This builder for chaining.
     */
    public Builder setNormalSideValue(int value) {
      
      normalSide_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.ledger.NormalSidePb normal_side = 5;</code>
     * @return The normalSide.
     */
    @java.lang.Override
    public com.exchange.proto.ledger.common.NormalSidePb getNormalSide() {
      @SuppressWarnings("deprecation")
      com.exchange.proto.ledger.common.NormalSidePb result = com.exchange.proto.ledger.common.NormalSidePb.valueOf(normalSide_);
      return result == null ? com.exchange.proto.ledger.common.NormalSidePb.UNRECOGNIZED : result;
    }
    /**
     * <code>.ledger.NormalSidePb normal_side = 5;</code>
     * @param value The normalSide to set.
     * @return This builder for chaining.
     */
    public Builder setNormalSide(com.exchange.proto.ledger.common.NormalSidePb value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      normalSide_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ledger.NormalSidePb normal_side = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearNormalSide() {
      
      normalSide_ = 0;
      onChanged();
      return this;
    }

    private int ownerType_ = 0;
    /**
     * <code>.ledger.OwnerTypePb owner_type = 6;</code>
     * @return The enum numeric value on the wire for ownerType.
     */
    @java.lang.Override public int getOwnerTypeValue() {
      return ownerType_;
    }
    /**
     * <code>.ledger.OwnerTypePb owner_type = 6;</code>
     * @param value The enum numeric value on the wire for ownerType to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerTypeValue(int value) {
      
      ownerType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.ledger.OwnerTypePb owner_type = 6;</code>
     * @return The ownerType.
     */
    @java.lang.Override
    public com.exchange.proto.ledger.common.OwnerTypePb getOwnerType() {
      @SuppressWarnings("deprecation")
      com.exchange.proto.ledger.common.OwnerTypePb result = com.exchange.proto.ledger.common.OwnerTypePb.valueOf(ownerType_);
      return result == null ? com.exchange.proto.ledger.common.OwnerTypePb.UNRECOGNIZED : result;
    }
    /**
     * <code>.ledger.OwnerTypePb owner_type = 6;</code>
     * @param value The ownerType to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerType(com.exchange.proto.ledger.common.OwnerTypePb value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      ownerType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ledger.OwnerTypePb owner_type = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearOwnerType() {
      
      ownerType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object ownerId_ = "";
    /**
     * <code>string owner_id = 7;</code>
     * @return The ownerId.
     */
    public java.lang.String getOwnerId() {
      java.lang.Object ref = ownerId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ownerId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string owner_id = 7;</code>
     * @return The bytes for ownerId.
     */
    public com.google.protobuf.ByteString
        getOwnerIdBytes() {
      java.lang.Object ref = ownerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ownerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string owner_id = 7;</code>
     * @param value The ownerId to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ownerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string owner_id = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearOwnerId() {
      
      ownerId_ = getDefaultInstance().getOwnerId();
      onChanged();
      return this;
    }
    /**
     * <code>string owner_id = 7;</code>
     * @param value The bytes for ownerId to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ownerId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ledger.CreateAccountRequestPb)
  }

  // @@protoc_insertion_point(class_scope:ledger.CreateAccountRequestPb)
  private static final com.exchange.proto.ledger.account.CreateAccountRequestPb DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.exchange.proto.ledger.account.CreateAccountRequestPb();
  }

  public static com.exchange.proto.ledger.account.CreateAccountRequestPb getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateAccountRequestPb>
      PARSER = new com.google.protobuf.AbstractParser<CreateAccountRequestPb>() {
    @java.lang.Override
    public CreateAccountRequestPb parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateAccountRequestPb(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateAccountRequestPb> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateAccountRequestPb> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.exchange.proto.ledger.account.CreateAccountRequestPb getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

