// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet/wallet_enum.proto

package com.exchange.proto.wallet.common;

/**
 * Protobuf enum {@code wallet.BusinessTypePb}
 */
public enum BusinessTypePb
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>BusinessTypePb_Unknown = 0;</code>
   */
  BusinessTypePb_Unknown(0),
  /**
   * <code>BusinessTypePb_Transfer = 1;</code>
   */
  BusinessTypePb_Transfer(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>BusinessTypePb_Unknown = 0;</code>
   */
  public static final int BusinessTypePb_Unknown_VALUE = 0;
  /**
   * <code>BusinessTypePb_Transfer = 1;</code>
   */
  public static final int BusinessTypePb_Transfer_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static BusinessTypePb valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static BusinessTypePb forNumber(int value) {
    switch (value) {
      case 0: return BusinessTypePb_Unknown;
      case 1: return BusinessTypePb_Transfer;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<BusinessTypePb>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      BusinessTypePb> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<BusinessTypePb>() {
          public BusinessTypePb findValueByNumber(int number) {
            return BusinessTypePb.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.exchange.proto.wallet.common.WalletEnum.getDescriptor().getEnumTypes().get(4);
  }

  private static final BusinessTypePb[] VALUES = values();

  public static BusinessTypePb valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private BusinessTypePb(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:wallet.BusinessTypePb)
}

