// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet/wallet_enum.proto

package com.exchange.proto.wallet.common;

/**
 * Protobuf enum {@code wallet.OperationTypePb}
 */
public enum OperationTypePb
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>OperationType_Unknown = 0;</code>
   */
  OperationType_Unknown(0),
  /**
   * <code>OperationType_Reserve = 1;</code>
   */
  OperationType_Reserve(1),
  /**
   * <pre>
   * confirm and transfer out in 2-step txn
   * </pre>
   *
   * <code>OperationType_Earmark = 2;</code>
   */
  OperationType_Earmark(2),
  /**
   * <code>OperationType_Release = 3;</code>
   */
  OperationType_Release(3),
  /**
   * <pre>
   * transfer out in atomic txn
   * </pre>
   *
   * <code>OperationType_Debit = 4;</code>
   */
  OperationType_Debit(4),
  /**
   * <code>OperationType_Credit = 5;</code>
   */
  OperationType_Credit(5),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>OperationType_Unknown = 0;</code>
   */
  public static final int OperationType_Unknown_VALUE = 0;
  /**
   * <code>OperationType_Reserve = 1;</code>
   */
  public static final int OperationType_Reserve_VALUE = 1;
  /**
   * <pre>
   * confirm and transfer out in 2-step txn
   * </pre>
   *
   * <code>OperationType_Earmark = 2;</code>
   */
  public static final int OperationType_Earmark_VALUE = 2;
  /**
   * <code>OperationType_Release = 3;</code>
   */
  public static final int OperationType_Release_VALUE = 3;
  /**
   * <pre>
   * transfer out in atomic txn
   * </pre>
   *
   * <code>OperationType_Debit = 4;</code>
   */
  public static final int OperationType_Debit_VALUE = 4;
  /**
   * <code>OperationType_Credit = 5;</code>
   */
  public static final int OperationType_Credit_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static OperationTypePb valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static OperationTypePb forNumber(int value) {
    switch (value) {
      case 0: return OperationType_Unknown;
      case 1: return OperationType_Reserve;
      case 2: return OperationType_Earmark;
      case 3: return OperationType_Release;
      case 4: return OperationType_Debit;
      case 5: return OperationType_Credit;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<OperationTypePb>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      OperationTypePb> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<OperationTypePb>() {
          public OperationTypePb findValueByNumber(int number) {
            return OperationTypePb.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.exchange.proto.wallet.common.WalletEnum.getDescriptor().getEnumTypes().get(6);
  }

  private static final OperationTypePb[] VALUES = values();

  public static OperationTypePb valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private OperationTypePb(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:wallet.OperationTypePb)
}

