// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet/wallet_enum.proto

package com.exchange.proto.wallet.common;

/**
 * Protobuf enum {@code wallet.TransactionStatusPb}
 */
public enum TransactionStatusPb
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>TransactionStatusPb_Unknown = 0;</code>
   */
  TransactionStatusPb_Unknown(0),
  /**
   * <code>TransactionStatusPb_Pending = 1;</code>
   */
  TransactionStatusPb_Pending(1),
  /**
   * <code>TransactionStatusPb_Completed = 2;</code>
   */
  TransactionStatusPb_Completed(2),
  /**
   * <code>TransactionStatusPb_Closed = 3;</code>
   */
  TransactionStatusPb_Closed(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>TransactionStatusPb_Unknown = 0;</code>
   */
  public static final int TransactionStatusPb_Unknown_VALUE = 0;
  /**
   * <code>TransactionStatusPb_Pending = 1;</code>
   */
  public static final int TransactionStatusPb_Pending_VALUE = 1;
  /**
   * <code>TransactionStatusPb_Completed = 2;</code>
   */
  public static final int TransactionStatusPb_Completed_VALUE = 2;
  /**
   * <code>TransactionStatusPb_Closed = 3;</code>
   */
  public static final int TransactionStatusPb_Closed_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TransactionStatusPb valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static TransactionStatusPb forNumber(int value) {
    switch (value) {
      case 0: return TransactionStatusPb_Unknown;
      case 1: return TransactionStatusPb_Pending;
      case 2: return TransactionStatusPb_Completed;
      case 3: return TransactionStatusPb_Closed;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TransactionStatusPb>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TransactionStatusPb> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TransactionStatusPb>() {
          public TransactionStatusPb findValueByNumber(int number) {
            return TransactionStatusPb.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.exchange.proto.wallet.common.WalletEnum.getDescriptor().getEnumTypes().get(3);
  }

  private static final TransactionStatusPb[] VALUES = values();

  public static TransactionStatusPb valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TransactionStatusPb(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:wallet.TransactionStatusPb)
}

