// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet/wallet_enum.proto

package com.exchange.proto.wallet.common;

public final class WalletEnum {
  private WalletEnum() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030wallet/wallet_enum.proto\022\006wallet*T\n\013Ow" +
      "nerTypePb\022\027\n\023OwnerTypePb_Unknown\020\000\022\026\n\022Ow" +
      "nerTypePb_System\020\001\022\024\n\020OwnerTypePb_User\020\002" +
      "*T\n\013ServiceIdPb\022\027\n\023ServiceIdPb_Unknown\020\000" +
      "\022\026\n\022ServiceIdPb_System\020\001\022\024\n\020ServiceIdPb_" +
      "User\020\002*P\n\021TransactionTypePb\022\035\n\031Transacti" +
      "onTypePb_Unknown\020\000\022\034\n\030TransactionTypePb_" +
      "Atomic\020\001*\232\001\n\023TransactionStatusPb\022\037\n\033Tran" +
      "sactionStatusPb_Unknown\020\000\022\037\n\033Transaction" +
      "StatusPb_Pending\020\001\022!\n\035TransactionStatusP" +
      "b_Completed\020\002\022\036\n\032TransactionStatusPb_Clo" +
      "sed\020\003*I\n\016BusinessTypePb\022\032\n\026BusinessTypeP" +
      "b_Unknown\020\000\022\033\n\027BusinessTypePb_Transfer\020\001" +
      "*}\n\014ActionTypePb\022\030\n\024ActionTypePb_Unknown" +
      "\020\000\022\030\n\024ActionTypePb_Reserve\020\001\022\034\n\030ActionTy" +
      "pePb_TransferOut\020\002\022\033\n\027ActionTypePb_Trans" +
      "ferIn\020\003B$\n com.exchange.proto.wallet.com" +
      "monP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
