// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet/wallet_enum.proto

package com.exchange.proto.wallet.common;

public final class WalletEnum {
  private WalletEnum() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030wallet/wallet_enum.proto\022\006wallet*T\n\013Ow" +
      "nerTypePb\022\027\n\023OwnerTypePb_Unknown\020\000\022\026\n\022Ow" +
      "nerTypePb_System\020\001\022\024\n\020OwnerTypePb_User\020\002" +
      "*T\n\013ServiceIdPb\022\027\n\023ServiceIdPb_Unknown\020\000" +
      "\022\026\n\022ServiceIdPb_System\020\001\022\024\n\020ServiceIdPb_" +
      "User\020\002*P\n\021TransactionTypePb\022\035\n\031Transacti" +
      "onTypePb_Unknown\020\000\022\034\n\030TransactionTypePb_" +
      "Atomic\020\001*\232\001\n\023TransactionStatusPb\022\037\n\033Tran" +
      "sactionStatusPb_Unknown\020\000\022\037\n\033Transaction" +
      "StatusPb_Pending\020\001\022!\n\035TransactionStatusP" +
      "b_Completed\020\002\022\036\n\032TransactionStatusPb_Clo" +
      "sed\020\003*I\n\016BusinessTypePb\022\032\n\026BusinessTypeP" +
      "b_Unknown\020\000\022\033\n\027BusinessTypePb_Transfer\020\001" +
      "*\227\001\n\014ActionTypePb\022\030\n\024ActionTypePb_Unknow" +
      "n\020\000\022\030\n\024ActionTypePb_Reserve\020\001\022\034\n\030ActionT" +
      "ypePb_TransferOut\020\002\022\033\n\027ActionTypePb_Tran" +
      "sferIn\020\003\022\030\n\024ActionTypePb_Release\020\004*\274\001\n\017O" +
      "perationTypePb\022\033\n\027OperationTypePb_Unknow" +
      "n\020\000\022\033\n\027OperationTypePb_Reserve\020\001\022\033\n\027Oper" +
      "ationTypePb_Earmark\020\002\022\033\n\027OperationTypePb" +
      "_Release\020\003\022\031\n\025OperationTypePb_Debit\020\004\022\032\n" +
      "\026OperationTypePb_Credit\020\005B$\n com.exchang" +
      "e.proto.wallet.commonP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
