// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet/wallet_common.proto

package com.exchange.proto.wallet.common;

public final class WalletCommon {
  private WalletCommon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032wallet/wallet_common.proto\022\006wallet*T\n\013" +
      "OwnerTypePb\022\027\n\023OwnerTypePb_Unknown\020\000\022\026\n\022" +
      "OwnerTypePb_System\020\001\022\024\n\020OwnerTypePb_User" +
      "\020\002*T\n\013ServiceIdPb\022\027\n\023ServiceIdPb_Unknown" +
      "\020\000\022\026\n\022ServiceIdPb_System\020\001\022\024\n\020ServiceIdP" +
      "b_User\020\002B$\n com.exchange.proto.wallet.co" +
      "mmonP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
